-- Additive seed: expands the mock catalog to ~100 routines / 18 instructors across 4 new styles.
-- Never edit 0002_catalog_seed.sql (already applied) — new catalog rows are appended here instead.

-- New style labels
INSERT INTO style_i18n (style_key, locale, label) VALUES
  ('jazz', 'he', 'ג''אז'),
  ('afro', 'he', 'אפרו'),
  ('dancehall', 'he', 'דאנסהול'),
  ('commercial', 'he', 'קומרשיאל'),
  ('jazz', 'en', 'Jazz'),
  ('afro', 'en', 'Afro'),
  ('dancehall', 'en', 'Dancehall'),
  ('commercial', 'en', 'Commercial');

-- New instructors
INSERT INTO instructors (slug, style, avatar, instagram_url) VALUES
  ('tali-mizrahi', 'jazz-funk', '/instructors/tali-mizrahi.jpg', 'https://www.instagram.com/'),
  ('yael-bar', 'jazz-funk', '/instructors/yael-bar.jpg', 'https://www.instagram.com/'),
  ('oran-ben-david', 'hip-hop', '/instructors/oran-ben-david.jpg', 'https://www.instagram.com/'),
  ('amit-sharabi', 'hip-hop', '/instructors/amit-sharabi.jpg', 'https://www.instagram.com/'),
  ('maya-rozin', 'heels', '/instructors/maya-rozin.jpg', 'https://www.instagram.com/'),
  ('noga-eliyahu', 'heels', '/instructors/noga-eliyahu.jpg', 'https://www.instagram.com/'),
  ('yasmin-kadosh', 'jazz', '/instructors/yasmin-kadosh.jpg', 'https://www.instagram.com/'),
  ('omer-tzur', 'jazz', '/instructors/omer-tzur.jpg', 'https://www.instagram.com/'),
  ('hila-ben-ari', 'jazz', '/instructors/hila-ben-ari.jpg', 'https://www.instagram.com/'),
  ('efrat-wolde', 'afro', '/instructors/efrat-wolde.jpg', 'https://www.instagram.com/'),
  ('yonatan-tesfaye', 'afro', '/instructors/yonatan-tesfaye.jpg', 'https://www.instagram.com/'),
  ('or-katz', 'dancehall', '/instructors/or-katz.jpg', 'https://www.instagram.com/'),
  ('tamir-levy', 'dancehall', '/instructors/tamir-levy.jpg', 'https://www.instagram.com/'),
  ('michal-buzaglo', 'commercial', '/instructors/michal-buzaglo.jpg', 'https://www.instagram.com/'),
  ('guy-ravid', 'commercial', '/instructors/guy-ravid.jpg', 'https://www.instagram.com/');

INSERT INTO instructor_i18n (slug, locale, name, bio) VALUES
  ('tali-mizrahi', 'he', 'טלי מזרחי', 'מלמדת ג''אז פאנק — גרוב ופרפורמנס.'),
  ('yael-bar', 'he', 'יעל בר', 'מלמדת ג''אז פאנק — מעברי משקל ושליטה בקצב.'),
  ('oran-ben-david', 'he', 'אורן בן דוד', 'מלמד היפ הופ — פוליריתמיקה וסטייל אישי.'),
  ('amit-sharabi', 'he', 'עמית שרעבי', 'מלמד היפ הופ — גרוב, מוזיקליות ופירוק שיטתי.'),
  ('maya-rozin', 'he', 'מאיה רוזין', 'מלמדת עקבים — יציבה ותנועתיות בעקב.'),
  ('noga-eliyahu', 'he', 'נגה אליהו', 'מלמדת עקבים — ביטחון וגרייס על הבמה.'),
  ('yasmin-kadosh', 'he', 'יסמין קדוש', 'מלמדת ג''אז — טכניקה, קו ומוזיקליות.'),
  ('omer-tzur', 'he', 'עומר צור', 'מלמד ג''אז — ליריקה ועומק רגשי בתנועה.'),
  ('hila-ben-ari', 'he', 'הילה בן ארי', 'מלמדת ג''אז — שליטה בגוף ופרפורמנס.'),
  ('efrat-wolde', 'he', 'אפרת וולדה', 'מלמדת אפרו — איזולציות, גרוב ואנרגייה.'),
  ('yonatan-tesfaye', 'he', 'יונתן טספאיה', 'מלמד אפרו — קצב אפריקאי אותנטי וקהילתיות.'),
  ('or-katz', 'he', 'אור כץ', 'מלמד דאנסהול — אנרגייה גבוהה וסטייל רחוב.'),
  ('tamir-levy', 'he', 'תמיר לוי', 'מלמד דאנסהול — בונס, גרוב ואטיטיוד.'),
  ('michal-buzaglo', 'he', 'מיכל בוזגלו', 'מלמדת קומרשיאל — שילוב טכניקה עם ביטחון על הבמה.'),
  ('guy-ravid', 'he', 'גיא רביד', 'מלמד קומרשיאל — קלינות תנועה וקצב מדויק.'),
  ('tali-mizrahi', 'en', 'Tali Mizrahi', 'Teaches Jazz Funk — groove and performance.'),
  ('yael-bar', 'en', 'Yael Bar', 'Teaches Jazz Funk — weight shifts and rhythm control.'),
  ('oran-ben-david', 'en', 'Oran Ben David', 'Teaches Hip Hop — polyrhythm and personal style.'),
  ('amit-sharabi', 'en', 'Amit Sharabi', 'Teaches Hip Hop — groove, musicality, and systematic breakdown.'),
  ('maya-rozin', 'en', 'Maya Rozin', 'Teaches Heels — posture and heel mobility.'),
  ('noga-eliyahu', 'en', 'Noga Eliyahu', 'Teaches Heels — confidence and stage grace.'),
  ('yasmin-kadosh', 'en', 'Yasmin Kadosh', 'Teaches Jazz — technique, line, and musicality.'),
  ('omer-tzur', 'en', 'Omer Tzur', 'Teaches Jazz — lyrical depth in movement.'),
  ('hila-ben-ari', 'en', 'Hila Ben Ari', 'Teaches Jazz — body control and performance.'),
  ('efrat-wolde', 'en', 'Efrat Wolde', 'Teaches Afro — isolations, groove, and energy.'),
  ('yonatan-tesfaye', 'en', 'Yonatan Tesfaye', 'Teaches Afro — authentic African rhythm and community.'),
  ('or-katz', 'en', 'Or Katz', 'Teaches Dancehall — high energy and street style.'),
  ('tamir-levy', 'en', 'Tamir Levy', 'Teaches Dancehall — bounce, groove, and attitude.'),
  ('michal-buzaglo', 'en', 'Michal Buzaglo', 'Teaches Commercial — blending technique with stage confidence.'),
  ('guy-ravid', 'en', 'Guy Ravid', 'Teaches Commercial — sharp movement and precise timing.');

-- New routines
INSERT INTO routines (
  slug, title, song_name, artist, instructor_slug, level, style, tags_json,
  bpm, length, poster, video_src, price_original, price_early_bird
) VALUES
  (
    'levitating-maya-azulai', 'Levitating', 'Levitating', 'Dua Lipa', 'maya-azulai',
    'intermediate', 'jazz-funk', '["jazz-funk","performance"]',
    '103 BPM', '3:23', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'dont-start-now-tali-mizrahi', 'Don''t Start Now', 'Don''t Start Now', 'Dua Lipa', 'tali-mizrahi',
    'advanced', 'jazz-funk', '["jazz-funk","groove"]',
    '124 BPM', '3:03', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'physical-yael-bar', 'Physical', 'Physical', 'Dua Lipa', 'yael-bar',
    'all-levels', 'jazz-funk', '["jazz-funk","musicality"]',
    '147 BPM', '3:13', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'about-damn-time-maya-azulai', 'About Damn Time', 'About Damn Time', 'Lizzo', 'maya-azulai',
    'intermediate', 'jazz-funk', '["jazz-funk","body-control"]',
    '109 BPM', '3:11', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'good-as-hell-tali-mizrahi', 'Good as Hell', 'Good as Hell', 'Lizzo', 'tali-mizrahi',
    'advanced', 'jazz-funk', '["jazz-funk","performance"]',
    '96 BPM', '2:39', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'flowers-yael-bar', 'Flowers', 'Flowers', 'Miley Cyrus', 'yael-bar',
    'all-levels', 'jazz-funk', '["jazz-funk","groove"]',
    '118 BPM', '3:20', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'shirt-maya-azulai', 'Shirt', 'Shirt', 'SZA', 'maya-azulai',
    'intermediate', 'jazz-funk', '["jazz-funk","musicality"]',
    '120 BPM', '3:01', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'blinding-lights-tali-mizrahi', 'Blinding Lights', 'Blinding Lights', 'The Weeknd', 'tali-mizrahi',
    'advanced', 'jazz-funk', '["jazz-funk","body-control"]',
    '171 BPM', '3:20', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'need-to-know-yael-bar', 'Need to Know', 'Need to Know', 'Doja Cat', 'yael-bar',
    'all-levels', 'jazz-funk', '["jazz-funk","performance"]',
    '130 BPM', '3:30', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'kiss-me-more-maya-azulai', 'Kiss Me More', 'Kiss Me More', 'Doja Cat ft. SZA', 'maya-azulai',
    'intermediate', 'jazz-funk', '["jazz-funk","groove"]',
    '111 BPM', '3:28', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'woman-tali-mizrahi', 'Woman', 'Woman', 'Doja Cat', 'tali-mizrahi',
    'advanced', 'jazz-funk', '["jazz-funk","musicality"]',
    '128 BPM', '2:52', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'nice-for-what-yael-bar', 'Nice For What', 'Nice For What', 'Drake', 'yael-bar',
    'all-levels', 'jazz-funk', '["jazz-funk","body-control"]',
    '93 BPM', '3:30', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'as-it-was-maya-azulai', 'As It Was', 'As It Was', 'Harry Styles', 'maya-azulai',
    'intermediate', 'jazz-funk', '["jazz-funk","performance"]',
    '174 BPM', '2:47', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'anti-hero-tali-mizrahi', 'Anti-Hero', 'Anti-Hero', 'Taylor Swift', 'tali-mizrahi',
    'advanced', 'jazz-funk', '["jazz-funk","groove"]',
    '97 BPM', '3:20', '/routine-poster-midnight-static.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'about-damn-time-daniel-cohen', 'About Damn Time', 'About Damn Time', 'Lizzo', 'daniel-cohen',
    'intermediate', 'hip-hop', '["hip-hop","performance"]',
    '109 BPM', '3:11', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'kill-bill-oran-ben-david', 'Kill Bill', 'Kill Bill', 'SZA', 'oran-ben-david',
    'advanced', 'hip-hop', '["hip-hop","groove"]',
    '89 BPM', '2:33', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'creepin-amit-sharabi', 'Creepin''', 'Creepin''', 'Metro Boomin, The Weeknd, 21 Savage', 'amit-sharabi',
    'all-levels', 'hip-hop', '["hip-hop","musicality"]',
    '98 BPM', '3:41', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'first-class-daniel-cohen', 'First Class', 'First Class', 'Jack Harlow', 'daniel-cohen',
    'intermediate', 'hip-hop', '["hip-hop","body-control"]',
    '107 BPM', '2:53', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'industry-baby-oran-ben-david', 'Industry Baby', 'Industry Baby', 'Lil Nas X & Jack Harlow', 'oran-ben-david',
    'advanced', 'hip-hop', '["hip-hop","performance"]',
    '150 BPM', '3:32', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'god-s-plan-amit-sharabi', 'God''s Plan', 'God''s Plan', 'Drake', 'amit-sharabi',
    'all-levels', 'hip-hop', '["hip-hop","groove"]',
    '77 BPM', '3:18', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'nice-for-what-daniel-cohen', 'Nice For What', 'Nice For What', 'Drake', 'daniel-cohen',
    'intermediate', 'hip-hop', '["hip-hop","musicality"]',
    '93 BPM', '3:30', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'savage-oran-ben-david', 'Savage', 'Savage', 'Megan Thee Stallion', 'oran-ben-david',
    'advanced', 'hip-hop', '["hip-hop","body-control"]',
    '127 BPM', '2:35', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'body-amit-sharabi', 'Body', 'Body', 'Megan Thee Stallion', 'amit-sharabi',
    'all-levels', 'hip-hop', '["hip-hop","performance"]',
    '123 BPM', '2:51', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'get-ur-freak-on-daniel-cohen', 'Get Ur Freak On', 'Get Ur Freak On', 'Missy Elliott', 'daniel-cohen',
    'intermediate', 'hip-hop', '["hip-hop","groove"]',
    '100 BPM', '3:53', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'work-it-oran-ben-david', 'Work It', 'Work It', 'Missy Elliott', 'oran-ben-david',
    'advanced', 'hip-hop', '["hip-hop","musicality"]',
    '100 BPM', '3:23', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'sicko-mode-amit-sharabi', 'Sicko Mode', 'Sicko Mode', 'Travis Scott', 'amit-sharabi',
    'all-levels', 'hip-hop', '["hip-hop","body-control"]',
    '155 BPM', '5:12', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'humble-daniel-cohen', 'Humble', 'Humble', 'Kendrick Lamar', 'daniel-cohen',
    'intermediate', 'hip-hop', '["hip-hop","performance"]',
    '150 BPM', '2:57', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'dna-oran-ben-david', 'DNA', 'DNA', 'Kendrick Lamar', 'oran-ben-david',
    'advanced', 'hip-hop', '["hip-hop","groove"]',
    '140 BPM', '3:05', '/routine-poster-neon-nights.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'kill-bill-noa-sagi', 'Kill Bill', 'Kill Bill', 'SZA', 'noa-sagi',
    'intermediate', 'heels', '["heels","performance"]',
    '89 BPM', '2:33', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'snooze-maya-rozin', 'Snooze', 'Snooze', 'SZA', 'maya-rozin',
    'advanced', 'heels', '["heels","groove"]',
    '77 BPM', '3:21', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'shirt-noga-eliyahu', 'Shirt', 'Shirt', 'SZA', 'noga-eliyahu',
    'all-levels', 'heels', '["heels","musicality"]',
    '120 BPM', '3:01', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'earned-it-noa-sagi', 'Earned It', 'Earned It', 'The Weeknd', 'noa-sagi',
    'intermediate', 'heels', '["heels","body-control"]',
    '120 BPM', '4:10', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'die-for-you-maya-rozin', 'Die For You', 'Die For You', 'The Weeknd', 'maya-rozin',
    'advanced', 'heels', '["heels","performance"]',
    '67 BPM', '4:20', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'creepin-noga-eliyahu', 'Creepin''', 'Creepin''', 'Metro Boomin, The Weeknd, 21 Savage', 'noga-eliyahu',
    'all-levels', 'heels', '["heels","groove"]',
    '98 BPM', '3:41', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'need-to-know-noa-sagi', 'Need to Know', 'Need to Know', 'Doja Cat', 'noa-sagi',
    'intermediate', 'heels', '["heels","musicality"]',
    '130 BPM', '3:30', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'kiss-me-more-maya-rozin', 'Kiss Me More', 'Kiss Me More', 'Doja Cat ft. SZA', 'maya-rozin',
    'advanced', 'heels', '["heels","body-control"]',
    '111 BPM', '3:28', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'body-party-noga-eliyahu', 'Body Party', 'Body Party', 'Ciara', 'noga-eliyahu',
    'all-levels', 'heels', '["heels","performance"]',
    '67 BPM', '4:00', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'ride-noa-sagi', 'Ride', 'Ride', 'Ciara', 'noa-sagi',
    'intermediate', 'heels', '["heels","groove"]',
    '65 BPM', '4:36', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    '2-on-maya-rozin', '2 On', '2 On', 'Tinashe', 'maya-rozin',
    'advanced', 'heels', '["heels","musicality"]',
    '100 BPM', '3:33', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'distraction-noga-eliyahu', 'Distraction', 'Distraction', 'Kehlani', 'noga-eliyahu',
    'all-levels', 'heels', '["heels","body-control"]',
    '100 BPM', '3:17', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'me-and-u-noa-sagi', 'Me & U', 'Me & U', 'Cassie', 'noa-sagi',
    'intermediate', 'heels', '["heels","performance"]',
    '130 BPM', '3:34', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'rock-the-boat-maya-rozin', 'Rock the Boat', 'Rock the Boat', 'Aaliyah', 'maya-rozin',
    'advanced', 'heels', '["heels","groove"]',
    '75 BPM', '4:04', '/routine-poster-velvet-heels.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'easy-on-me-yasmin-kadosh', 'Easy On Me', 'Easy On Me', 'Adele', 'yasmin-kadosh',
    'intermediate', 'jazz', '["jazz","performance"]',
    '62 BPM', '3:44', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'rolling-in-the-deep-omer-tzur', 'Rolling in the Deep', 'Rolling in the Deep', 'Adele', 'omer-tzur',
    'advanced', 'jazz', '["jazz","groove"]',
    '105 BPM', '3:48', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'stay-with-me-hila-ben-ari', 'Stay With Me', 'Stay With Me', 'Sam Smith', 'hila-ben-ari',
    'all-levels', 'jazz', '["jazz","musicality"]',
    '79 BPM', '2:53', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'unholy-yasmin-kadosh', 'Unholy', 'Unholy', 'Sam Smith ft. Kim Petras', 'yasmin-kadosh',
    'intermediate', 'jazz', '["jazz","body-control"]',
    '131 BPM', '2:36', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'ocean-eyes-omer-tzur', 'Ocean Eyes', 'Ocean Eyes', 'Billie Eilish', 'omer-tzur',
    'advanced', 'jazz', '["jazz","performance"]',
    '79 BPM', '3:20', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'happier-than-ever-hila-ben-ari', 'Happier Than Ever', 'Happier Than Ever', 'Billie Eilish', 'hila-ben-ari',
    'all-levels', 'jazz', '["jazz","groove"]',
    '87 BPM', '4:58', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'best-part-yasmin-kadosh', 'Best Part', 'Best Part', 'H.E.R. ft. Daniel Caesar', 'yasmin-kadosh',
    'intermediate', 'jazz', '["jazz","musicality"]',
    '68 BPM', '3:29', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'someone-you-loved-omer-tzur', 'Someone You Loved', 'Someone You Loved', 'Lewis Capaldi', 'omer-tzur',
    'advanced', 'jazz', '["jazz","body-control"]',
    '110 BPM', '3:02', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'my-hair-hila-ben-ari', 'my hair', 'my hair', 'Ariana Grande', 'hila-ben-ari',
    'all-levels', 'jazz', '["jazz","performance"]',
    '55 BPM', '2:41', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'be-honest-yasmin-kadosh', 'Be Honest', 'Be Honest', 'Jorja Smith', 'yasmin-kadosh',
    'intermediate', 'jazz', '["jazz","groove"]',
    '100 BPM', '3:29', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'if-i-aint-got-you-omer-tzur', 'If I Ain''t Got You', 'If I Ain''t Got You', 'Alicia Keys', 'omer-tzur',
    'advanced', 'jazz', '["jazz","musicality"]',
    '94 BPM', '3:48', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'all-of-me-hila-ben-ari', 'All of Me', 'All of Me', 'John Legend', 'hila-ben-ari',
    'all-levels', 'jazz', '["jazz","body-control"]',
    '63 BPM', '4:29', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'get-you-yasmin-kadosh', 'Get You', 'Get You', 'Daniel Caesar ft. Kali Uchis', 'yasmin-kadosh',
    'intermediate', 'jazz', '["jazz","performance"]',
    '85 BPM', '4:08', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'toronto-omer-tzur', 'Toronto', 'Toronto', 'Snoh Aalegra', 'omer-tzur',
    'advanced', 'jazz', '["jazz","groove"]',
    '88 BPM', '3:07', '/routine-poster-jazz-glow.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'be-honest-efrat-wolde', 'Be Honest', 'Be Honest', 'Jorja Smith', 'efrat-wolde',
    'intermediate', 'afro', '["afro","performance"]',
    '100 BPM', '3:29', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'higher-yonatan-tesfaye', 'Higher', 'Higher', 'Tems', 'yonatan-tesfaye',
    'advanced', 'afro', '["afro","groove"]',
    '100 BPM', '3:14', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'last-last-efrat-wolde', 'Last Last', 'Last Last', 'Burna Boy', 'efrat-wolde',
    'all-levels', 'afro', '["afro","musicality"]',
    '103 BPM', '3:15', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'kilometre-yonatan-tesfaye', 'Kilometre', 'Kilometre', 'Burna Boy', 'yonatan-tesfaye',
    'intermediate', 'afro', '["afro","body-control"]',
    '105 BPM', '3:33', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'essence-efrat-wolde', 'Essence', 'Essence', 'Wizkid ft. Tems', 'efrat-wolde',
    'advanced', 'afro', '["afro","performance"]',
    '103 BPM', '4:08', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'ojuelegba-yonatan-tesfaye', 'Ojuelegba', 'Ojuelegba', 'Wizkid', 'yonatan-tesfaye',
    'all-levels', 'afro', '["afro","groove"]',
    '100 BPM', '3:47', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'fall-efrat-wolde', 'Fall', 'Fall', 'Davido', 'efrat-wolde',
    'intermediate', 'afro', '["afro","musicality"]',
    '102 BPM', '4:07', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'unavailable-yonatan-tesfaye', 'Unavailable', 'Unavailable', 'Davido ft. Musa Keys', 'yonatan-tesfaye',
    'advanced', 'afro', '["afro","body-control"]',
    '107 BPM', '2:58', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'calm-down-efrat-wolde', 'Calm Down', 'Calm Down', 'Rema', 'efrat-wolde',
    'all-levels', 'afro', '["afro","performance"]',
    '107 BPM', '3:39', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'dumebi-yonatan-tesfaye', 'Dumebi', 'Dumebi', 'Rema', 'yonatan-tesfaye',
    'intermediate', 'afro', '["afro","groove"]',
    '104 BPM', '3:17', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'love-nwantiti-efrat-wolde', 'Love Nwantiti', 'Love Nwantiti', 'CKay', 'efrat-wolde',
    'advanced', 'afro', '["afro","musicality"]',
    '108 BPM', '2:47', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'free-mind-yonatan-tesfaye', 'Free Mind', 'Free Mind', 'Tems', 'yonatan-tesfaye',
    'all-levels', 'afro', '["afro","body-control"]',
    '105 BPM', '3:47', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'peru-efrat-wolde', 'Peru', 'Peru', 'Fireboy DML', 'efrat-wolde',
    'intermediate', 'afro', '["afro","performance"]',
    '103 BPM', '2:52', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'rush-yonatan-tesfaye', 'Rush', 'Rush', 'Ayra Starr', 'yonatan-tesfaye',
    'advanced', 'afro', '["afro","groove"]',
    '103 BPM', '2:50', '/routine-poster-afro-sunburst.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'terminator-or-katz', 'Terminator', 'Terminator', 'Asake', 'or-katz',
    'intermediate', 'dancehall', '["dancehall","performance"]',
    '103 BPM', '2:53', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'touch-it-tamir-levy', 'Touch It', 'Touch It', 'KiDi', 'tamir-levy',
    'advanced', 'dancehall', '["dancehall","groove"]',
    '105 BPM', '3:20', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'temperature-or-katz', 'Temperature', 'Temperature', 'Sean Paul', 'or-katz',
    'all-levels', 'dancehall', '["dancehall","musicality"]',
    '98 BPM', '3:24', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'get-busy-tamir-levy', 'Get Busy', 'Get Busy', 'Sean Paul', 'tamir-levy',
    'intermediate', 'dancehall', '["dancehall","body-control"]',
    '95 BPM', '3:36', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'family-or-katz', 'Family', 'Family', 'Popcaan', 'or-katz',
    'advanced', 'dancehall', '["dancehall","performance"]',
    '101 BPM', '3:20', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'ova-dweet-tamir-levy', 'Ova Dweet', 'Ova Dweet', 'Popcaan', 'tamir-levy',
    'all-levels', 'dancehall', '["dancehall","groove"]',
    '100 BPM', '3:12', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'blessed-or-katz', 'Blessed', 'Blessed', 'Shenseea', 'or-katz',
    'intermediate', 'dancehall', '["dancehall","musicality"]',
    '100 BPM', '3:03', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'lick-tamir-levy', 'Lick', 'Lick', 'Shenseea', 'tamir-levy',
    'advanced', 'dancehall', '["dancehall","body-control"]',
    '98 BPM', '3:07', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'bruk-off-yuh-back-or-katz', 'Bruk Off Yuh Back', 'Bruk Off Yuh Back', 'Konshens', 'or-katz',
    'all-levels', 'dancehall', '["dancehall","performance"]',
    '105 BPM', '3:05', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'fever-tamir-levy', 'Fever', 'Fever', 'Vybz Kartel', 'tamir-levy',
    'intermediate', 'dancehall', '["dancehall","groove"]',
    '100 BPM', '3:12', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'so-mi-like-it-or-katz', 'So Mi Like It', 'So Mi Like It', 'Spice', 'or-katz',
    'advanced', 'dancehall', '["dancehall","musicality"]',
    '103 BPM', '2:58', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'coke-tamir-levy', 'Coke', 'Coke', 'Skillibeng', 'tamir-levy',
    'all-levels', 'dancehall', '["dancehall","body-control"]',
    '100 BPM', '2:40', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'ina-real-life-or-katz', 'Ina Real Life', 'Ina Real Life', 'Alkaline', 'or-katz',
    'intermediate', 'dancehall', '["dancehall","performance"]',
    '98 BPM', '3:10', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'owe-me-nothing-tamir-levy', 'Owe Me Nothing', 'Owe Me Nothing', 'Dexta Daps', 'tamir-levy',
    'advanced', 'dancehall', '["dancehall","groove"]',
    '95 BPM', '3:36', '/routine-poster-dancehall-block.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'cant-stop-the-feeling-michal-buzaglo', 'Can''t Stop the Feeling', 'Can''t Stop the Feeling', 'Justin Timberlake', 'michal-buzaglo',
    'intermediate', 'commercial', '["commercial","performance"]',
    '113 BPM', '3:56', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'unholy-guy-ravid', 'Unholy', 'Unholy', 'Sam Smith ft. Kim Petras', 'guy-ravid',
    'advanced', 'commercial', '["commercial","groove"]',
    '131 BPM', '2:36', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'unavailable-michal-buzaglo', 'Unavailable', 'Unavailable', 'Davido ft. Musa Keys', 'michal-buzaglo',
    'all-levels', 'commercial', '["commercial","musicality"]',
    '107 BPM', '2:58', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'calm-down-guy-ravid', 'Calm Down', 'Calm Down', 'Rema', 'guy-ravid',
    'intermediate', 'commercial', '["commercial","body-control"]',
    '107 BPM', '3:39', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'rush-michal-buzaglo', 'Rush', 'Rush', 'Ayra Starr', 'michal-buzaglo',
    'advanced', 'commercial', '["commercial","performance"]',
    '103 BPM', '2:50', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'sad-girlz-luv-money-guy-ravid', 'Sad Girlz Luv Money', 'Sad Girlz Luv Money', 'Amaarae', 'guy-ravid',
    'all-levels', 'commercial', '["commercial","groove"]',
    '100 BPM', '2:37', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'blessed-michal-buzaglo', 'Blessed', 'Blessed', 'Shenseea', 'michal-buzaglo',
    'intermediate', 'commercial', '["commercial","musicality"]',
    '100 BPM', '3:03', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    'break-my-soul-guy-ravid', 'Break My Soul', 'Break My Soul', 'Beyoncé', 'guy-ravid',
    'advanced', 'commercial', '["commercial","body-control"]',
    '115 BPM', '4:38', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'formation-michal-buzaglo', 'Formation', 'Formation', 'Beyoncé', 'michal-buzaglo',
    'all-levels', 'commercial', '["commercial","performance"]',
    '115 BPM', '3:26', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  ),
  (
    'umbrella-guy-ravid', 'Umbrella', 'Umbrella', 'Rihanna', 'guy-ravid',
    'intermediate', 'commercial', '["commercial","groove"]',
    '87 BPM', '4:36', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    59, 39
  ),
  (
    'dont-stop-the-music-michal-buzaglo', 'Don''t Stop the Music', 'Don''t Stop the Music', 'Rihanna', 'michal-buzaglo',
    'advanced', 'commercial', '["commercial","musicality"]',
    '123 BPM', '4:33', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    69, 49
  ),
  (
    '7-rings-guy-ravid', '7 rings', '7 rings', 'Ariana Grande', 'guy-ravid',
    'all-levels', 'commercial', '["commercial","body-control"]',
    '140 BPM', '2:58', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    79, 59
  ),
  (
    'break-free-michal-buzaglo', 'Break Free', 'Break Free', 'Ariana Grande', 'michal-buzaglo',
    'intermediate', 'commercial', '["commercial","performance"]',
    '128 BPM', '3:34', '/routine-poster-commercial-spotlight.png',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    49, 29
  );

INSERT INTO routine_i18n (slug, locale, technique, description) VALUES
  ('levitating-maya-azulai', 'he', 'מעברי משקל קרקעיים ופרפורמנס', 'קומבינציית ג''אז פאנק אנרגטית על "Levitating" של Dua Lipa, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('dont-start-now-tali-mizrahi', 'he', 'גרוב, איזולציות ודיוק תנועה', 'שגרת ג''אז פאנק קצבית ל"Don''t Start Now" (Dua Lipa), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('physical-yael-bar', 'he', 'קצב, ליין ואנרגיית ביצוע', 'קומבינציית ג''אז פאנק אנרגטית על "Physical" של Dua Lipa, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('about-damn-time-maya-azulai', 'he', 'מעברי משקל קרקעיים ופרפורמנס', 'שגרת ג''אז פאנק קצבית ל"About Damn Time" (Lizzo), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('good-as-hell-tali-mizrahi', 'he', 'גרוב, איזולציות ודיוק תנועה', 'קומבינציית ג''אז פאנק אנרגטית על "Good as Hell" של Lizzo, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('flowers-yael-bar', 'he', 'קצב, ליין ואנרגיית ביצוע', 'שגרת ג''אז פאנק קצבית ל"Flowers" (Miley Cyrus), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('shirt-maya-azulai', 'he', 'מעברי משקל קרקעיים ופרפורמנס', 'קומבינציית ג''אז פאנק אנרגטית על "Shirt" של SZA, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('blinding-lights-tali-mizrahi', 'he', 'גרוב, איזולציות ודיוק תנועה', 'שגרת ג''אז פאנק קצבית ל"Blinding Lights" (The Weeknd), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('need-to-know-yael-bar', 'he', 'קצב, ליין ואנרגיית ביצוע', 'קומבינציית ג''אז פאנק אנרגטית על "Need to Know" של Doja Cat, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('kiss-me-more-maya-azulai', 'he', 'מעברי משקל קרקעיים ופרפורמנס', 'שגרת ג''אז פאנק קצבית ל"Kiss Me More" (Doja Cat ft. SZA), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('woman-tali-mizrahi', 'he', 'גרוב, איזולציות ודיוק תנועה', 'קומבינציית ג''אז פאנק אנרגטית על "Woman" של Doja Cat, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('nice-for-what-yael-bar', 'he', 'קצב, ליין ואנרגיית ביצוע', 'שגרת ג''אז פאנק קצבית ל"Nice For What" (Drake), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('as-it-was-maya-azulai', 'he', 'מעברי משקל קרקעיים ופרפורמנס', 'קומבינציית ג''אז פאנק אנרגטית על "As It Was" של Harry Styles, עם דגש על גרוב ופרפורמנס — מושלמת לרקדנים שרוצים לשדרג את הביטוי האישי שלהם על הבמה.'),
  ('anti-hero-tali-mizrahi', 'he', 'גרוב, איזולציות ודיוק תנועה', 'שגרת ג''אז פאנק קצבית ל"Anti-Hero" (Taylor Swift), שמלמדת שליטה במעברי משקל ותנועה חלקה מבלי לוותר על אנרגייה.'),
  ('about-damn-time-daniel-cohen', 'he', 'גרוב, פוליריתמיקה ועבודת רצפה', 'קומבינציית היפ הופ עוצמתית ל"About Damn Time" של Lizzo, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('kill-bill-oran-ben-david', 'he', 'פירוק שיטתי וקואורדינציה', 'שגרת היפ הופ עם דגש טכני גבוה ל"Kill Bill" (SZA) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('creepin-amit-sharabi', 'he', 'עוצמה, גרוב וסטייל אישי', 'קומבינציית היפ הופ עוצמתית ל"Creepin''" של Metro Boomin, The Weeknd, 21 Savage, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('first-class-daniel-cohen', 'he', 'גרוב, פוליריתמיקה ועבודת רצפה', 'שגרת היפ הופ עם דגש טכני גבוה ל"First Class" (Jack Harlow) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('industry-baby-oran-ben-david', 'he', 'פירוק שיטתי וקואורדינציה', 'קומבינציית היפ הופ עוצמתית ל"Industry Baby" של Lil Nas X & Jack Harlow, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('god-s-plan-amit-sharabi', 'he', 'עוצמה, גרוב וסטייל אישי', 'שגרת היפ הופ עם דגש טכני גבוה ל"God''s Plan" (Drake) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('nice-for-what-daniel-cohen', 'he', 'גרוב, פוליריתמיקה ועבודת רצפה', 'קומבינציית היפ הופ עוצמתית ל"Nice For What" של Drake, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('savage-oran-ben-david', 'he', 'פירוק שיטתי וקואורדינציה', 'שגרת היפ הופ עם דגש טכני גבוה ל"Savage" (Megan Thee Stallion) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('body-amit-sharabi', 'he', 'עוצמה, גרוב וסטייל אישי', 'קומבינציית היפ הופ עוצמתית ל"Body" של Megan Thee Stallion, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('get-ur-freak-on-daniel-cohen', 'he', 'גרוב, פוליריתמיקה ועבודת רצפה', 'שגרת היפ הופ עם דגש טכני גבוה ל"Get Ur Freak On" (Missy Elliott) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('work-it-oran-ben-david', 'he', 'פירוק שיטתי וקואורדינציה', 'קומבינציית היפ הופ עוצמתית ל"Work It" של Missy Elliott, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('sicko-mode-amit-sharabi', 'he', 'עוצמה, גרוב וסטייל אישי', 'שגרת היפ הופ עם דגש טכני גבוה ל"Sicko Mode" (Travis Scott) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('humble-daniel-cohen', 'he', 'גרוב, פוליריתמיקה ועבודת רצפה', 'קומבינציית היפ הופ עוצמתית ל"Humble" של Kendrick Lamar, שבנויה על גרוב עמוק ומעברים חדים בין התנועות.'),
  ('dna-oran-ben-david', 'he', 'פירוק שיטתי וקואורדינציה', 'שגרת היפ הופ עם דגש טכני גבוה ל"DNA" (Kendrick Lamar) — לרקדנים שרוצים להעמיק בסגנון ובפירוק התנועות.'),
  ('kill-bill-noa-sagi', 'he', 'אורך קו, שליטה בעקב ופרפורמנס', 'קומבינציית עקבים מפתה ובטוחה ל"Kill Bill" של SZA, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('snooze-maya-rozin', 'he', 'יציבה, בטחון ותנועתיות בעקב', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Snooze" (SZA).'),
  ('shirt-noga-eliyahu', 'he', 'גרייס וקונטרול על הבמה', 'קומבינציית עקבים מפתה ובטוחה ל"Shirt" של SZA, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('earned-it-noa-sagi', 'he', 'אורך קו, שליטה בעקב ופרפורמנס', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Earned It" (The Weeknd).'),
  ('die-for-you-maya-rozin', 'he', 'יציבה, בטחון ותנועתיות בעקב', 'קומבינציית עקבים מפתה ובטוחה ל"Die For You" של The Weeknd, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('creepin-noga-eliyahu', 'he', 'גרייס וקונטרול על הבמה', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Creepin''" (Metro Boomin, The Weeknd, 21 Savage).'),
  ('need-to-know-noa-sagi', 'he', 'אורך קו, שליטה בעקב ופרפורמנס', 'קומבינציית עקבים מפתה ובטוחה ל"Need to Know" של Doja Cat, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('kiss-me-more-maya-rozin', 'he', 'יציבה, בטחון ותנועתיות בעקב', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Kiss Me More" (Doja Cat ft. SZA).'),
  ('body-party-noga-eliyahu', 'he', 'גרייס וקונטרול על הבמה', 'קומבינציית עקבים מפתה ובטוחה ל"Body Party" של Ciara, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('ride-noa-sagi', 'he', 'אורך קו, שליטה בעקב ופרפורמנס', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Ride" (Ciara).'),
  ('2-on-maya-rozin', 'he', 'יציבה, בטחון ותנועתיות בעקב', 'קומבינציית עקבים מפתה ובטוחה ל"2 On" של Tinashe, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('distraction-noga-eliyahu', 'he', 'גרייס וקונטרול על הבמה', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Distraction" (Kehlani).'),
  ('me-and-u-noa-sagi', 'he', 'אורך קו, שליטה בעקב ופרפורמנס', 'קומבינציית עקבים מפתה ובטוחה ל"Me & U" של Cassie, שמלמדת איך לשלוט בעקב מבלי לוותר על טכניקה.'),
  ('rock-the-boat-maya-rozin', 'he', 'יציבה, בטחון ותנועתיות בעקב', 'שגרת עקבים עם דגשים על יציבה, אורך קו ופרפורמנס, ל"Rock the Boat" (Aaliyah).'),
  ('easy-on-me-yasmin-kadosh', 'he', 'טכניקה, קו ועומק רגשי', 'קומבינציית ג''אז ליריקה ל"Easy On Me" של Adele, עם דגש על עומק רגשי ומוזיקליות.'),
  ('rolling-in-the-deep-omer-tzur', 'he', 'מוזיקליות ושליטה בגוף', 'שגרת ג''אז טכנית ל"Rolling in the Deep" (Adele) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('stay-with-me-hila-ben-ari', 'he', 'ליריקה ופרפורמנס', 'קומבינציית ג''אז ליריקה ל"Stay With Me" של Sam Smith, עם דגש על עומק רגשי ומוזיקליות.'),
  ('unholy-yasmin-kadosh', 'he', 'טכניקה, קו ועומק רגשי', 'שגרת ג''אז טכנית ל"Unholy" (Sam Smith ft. Kim Petras) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('ocean-eyes-omer-tzur', 'he', 'מוזיקליות ושליטה בגוף', 'קומבינציית ג''אז ליריקה ל"Ocean Eyes" של Billie Eilish, עם דגש על עומק רגשי ומוזיקליות.'),
  ('happier-than-ever-hila-ben-ari', 'he', 'ליריקה ופרפורמנס', 'שגרת ג''אז טכנית ל"Happier Than Ever" (Billie Eilish) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('best-part-yasmin-kadosh', 'he', 'טכניקה, קו ועומק רגשי', 'קומבינציית ג''אז ליריקה ל"Best Part" של H.E.R. ft. Daniel Caesar, עם דגש על עומק רגשי ומוזיקליות.'),
  ('someone-you-loved-omer-tzur', 'he', 'מוזיקליות ושליטה בגוף', 'שגרת ג''אז טכנית ל"Someone You Loved" (Lewis Capaldi) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('my-hair-hila-ben-ari', 'he', 'ליריקה ופרפורמנס', 'קומבינציית ג''אז ליריקה ל"my hair" של Ariana Grande, עם דגש על עומק רגשי ומוזיקליות.'),
  ('be-honest-yasmin-kadosh', 'he', 'טכניקה, קו ועומק רגשי', 'שגרת ג''אז טכנית ל"Be Honest" (Jorja Smith) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('if-i-aint-got-you-omer-tzur', 'he', 'מוזיקליות ושליטה בגוף', 'קומבינציית ג''אז ליריקה ל"If I Ain''t Got You" של Alicia Keys, עם דגש על עומק רגשי ומוזיקליות.'),
  ('all-of-me-hila-ben-ari', 'he', 'ליריקה ופרפורמנס', 'שגרת ג''אז טכנית ל"All of Me" (John Legend) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('get-you-yasmin-kadosh', 'he', 'טכניקה, קו ועומק רגשי', 'קומבינציית ג''אז ליריקה ל"Get You" של Daniel Caesar ft. Kali Uchis, עם דגש על עומק רגשי ומוזיקליות.'),
  ('toronto-omer-tzur', 'he', 'מוזיקליות ושליטה בגוף', 'שגרת ג''אז טכנית ל"Toronto" (Snoh Aalegra) — לרקדנים שרוצים לחדד קו וביטוי בגוף.'),
  ('be-honest-efrat-wolde', 'he', 'איזולציות, גרוב ואנרגייה קבוצתית', 'קומבינציית אפרו קצבית ל"Be Honest" של Jorja Smith, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('higher-yonatan-tesfaye', 'he', 'קצב אפריקאי אותנטי ותנועתיות חופשית', 'שגרת אפרו שמחה ל"Higher" (Tems) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('last-last-efrat-wolde', 'he', 'שליחת אנרגייה ושמחת תנועה', 'קומבינציית אפרו קצבית ל"Last Last" של Burna Boy, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('kilometre-yonatan-tesfaye', 'he', 'איזולציות, גרוב ואנרגייה קבוצתית', 'שגרת אפרו שמחה ל"Kilometre" (Burna Boy) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('essence-efrat-wolde', 'he', 'קצב אפריקאי אותנטי ותנועתיות חופשית', 'קומבינציית אפרו קצבית ל"Essence" של Wizkid ft. Tems, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('ojuelegba-yonatan-tesfaye', 'he', 'שליחת אנרגייה ושמחת תנועה', 'שגרת אפרו שמחה ל"Ojuelegba" (Wizkid) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('fall-efrat-wolde', 'he', 'איזולציות, גרוב ואנרגייה קבוצתית', 'קומבינציית אפרו קצבית ל"Fall" של Davido, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('unavailable-yonatan-tesfaye', 'he', 'קצב אפריקאי אותנטי ותנועתיות חופשית', 'שגרת אפרו שמחה ל"Unavailable" (Davido ft. Musa Keys) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('calm-down-efrat-wolde', 'he', 'שליחת אנרגייה ושמחת תנועה', 'קומבינציית אפרו קצבית ל"Calm Down" של Rema, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('dumebi-yonatan-tesfaye', 'he', 'איזולציות, גרוב ואנרגייה קבוצתית', 'שגרת אפרו שמחה ל"Dumebi" (Rema) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('love-nwantiti-efrat-wolde', 'he', 'קצב אפריקאי אותנטי ותנועתיות חופשית', 'קומבינציית אפרו קצבית ל"Love Nwantiti" של CKay, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('free-mind-yonatan-tesfaye', 'he', 'שליחת אנרגייה ושמחת תנועה', 'שגרת אפרו שמחה ל"Free Mind" (Tems) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('peru-efrat-wolde', 'he', 'איזולציות, גרוב ואנרגייה קבוצתית', 'קומבינציית אפרו קצבית ל"Peru" של Fireboy DML, עם דגש על איזולציות ואנרגייה קבוצתית.'),
  ('rush-yonatan-tesfaye', 'he', 'קצב אפריקאי אותנטי ותנועתיות חופשית', 'שגרת אפרו שמחה ל"Rush" (Ayra Starr) — קצב אפריקאי אותנטי ותנועתיות חופשית.'),
  ('terminator-or-katz', 'he', 'בונס, גרוב ואטיטיוד', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Terminator" של Asake, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('touch-it-tamir-levy', 'he', 'עוצמה ודיוק בתנועות רגליים', 'שגרת דאנסהול באנרגייה גבוהה ל"Touch It" (KiDi) — עוצמה ודיוק בתנועות הרגליים.'),
  ('temperature-or-katz', 'he', 'אנרגייה גבוהה וסטייל רחוב', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Temperature" של Sean Paul, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('get-busy-tamir-levy', 'he', 'בונס, גרוב ואטיטיוד', 'שגרת דאנסהול באנרגייה גבוהה ל"Get Busy" (Sean Paul) — עוצמה ודיוק בתנועות הרגליים.'),
  ('family-or-katz', 'he', 'עוצמה ודיוק בתנועות רגליים', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Family" של Popcaan, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('ova-dweet-tamir-levy', 'he', 'אנרגייה גבוהה וסטייל רחוב', 'שגרת דאנסהול באנרגייה גבוהה ל"Ova Dweet" (Popcaan) — עוצמה ודיוק בתנועות הרגליים.'),
  ('blessed-or-katz', 'he', 'בונס, גרוב ואטיטיוד', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Blessed" של Shenseea, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('lick-tamir-levy', 'he', 'עוצמה ודיוק בתנועות רגליים', 'שגרת דאנסהול באנרגייה גבוהה ל"Lick" (Shenseea) — עוצמה ודיוק בתנועות הרגליים.'),
  ('bruk-off-yuh-back-or-katz', 'he', 'אנרגייה גבוהה וסטייל רחוב', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Bruk Off Yuh Back" של Konshens, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('fever-tamir-levy', 'he', 'בונס, גרוב ואטיטיוד', 'שגרת דאנסהול באנרגייה גבוהה ל"Fever" (Vybz Kartel) — עוצמה ודיוק בתנועות הרגליים.'),
  ('so-mi-like-it-or-katz', 'he', 'עוצמה ודיוק בתנועות רגליים', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"So Mi Like It" של Spice, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('coke-tamir-levy', 'he', 'אנרגייה גבוהה וסטייל רחוב', 'שגרת דאנסהול באנרגייה גבוהה ל"Coke" (Skillibeng) — עוצמה ודיוק בתנועות הרגליים.'),
  ('ina-real-life-or-katz', 'he', 'בונס, גרוב ואטיטיוד', 'קומבינציית דאנסהול עם בונס ואטיטיוד ל"Ina Real Life" של Alkaline, לרקדנים שרוצים סטייל רחוב אמיתי.'),
  ('owe-me-nothing-tamir-levy', 'he', 'עוצמה ודיוק בתנועות רגליים', 'שגרת דאנסהול באנרגייה גבוהה ל"Owe Me Nothing" (Dexta Daps) — עוצמה ודיוק בתנועות הרגליים.'),
  ('cant-stop-the-feeling-michal-buzaglo', 'he', 'פרפורמנס וסטייל מסחרי חד', 'קומבינציית קומרשיאל חדה ל"Can''t Stop the Feeling" של Justin Timberlake, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('unholy-guy-ravid', 'he', 'שילוב טכניקה עם ביטחון על הבמה', 'שגרת קומרשיאל עם טיימינג מדויק ל"Unholy" (Sam Smith ft. Kim Petras) — סטייל מסחרי לביצועים ואודישנים.'),
  ('unavailable-michal-buzaglo', 'he', 'קלינות תנועה וטיימינג מדויק', 'קומבינציית קומרשיאל חדה ל"Unavailable" של Davido ft. Musa Keys, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('calm-down-guy-ravid', 'he', 'פרפורמנס וסטייל מסחרי חד', 'שגרת קומרשיאל עם טיימינג מדויק ל"Calm Down" (Rema) — סטייל מסחרי לביצועים ואודישנים.'),
  ('rush-michal-buzaglo', 'he', 'שילוב טכניקה עם ביטחון על הבמה', 'קומבינציית קומרשיאל חדה ל"Rush" של Ayra Starr, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('sad-girlz-luv-money-guy-ravid', 'he', 'קלינות תנועה וטיימינג מדויק', 'שגרת קומרשיאל עם טיימינג מדויק ל"Sad Girlz Luv Money" (Amaarae) — סטייל מסחרי לביצועים ואודישנים.'),
  ('blessed-michal-buzaglo', 'he', 'פרפורמנס וסטייל מסחרי חד', 'קומבינציית קומרשיאל חדה ל"Blessed" של Shenseea, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('break-my-soul-guy-ravid', 'he', 'שילוב טכניקה עם ביטחון על הבמה', 'שגרת קומרשיאל עם טיימינג מדויק ל"Break My Soul" (Beyoncé) — סטייל מסחרי לביצועים ואודישנים.'),
  ('formation-michal-buzaglo', 'he', 'קלינות תנועה וטיימינג מדויק', 'קומבינציית קומרשיאל חדה ל"Formation" של Beyoncé, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('umbrella-guy-ravid', 'he', 'פרפורמנס וסטייל מסחרי חד', 'שגרת קומרשיאל עם טיימינג מדויק ל"Umbrella" (Rihanna) — סטייל מסחרי לביצועים ואודישנים.'),
  ('dont-stop-the-music-michal-buzaglo', 'he', 'שילוב טכניקה עם ביטחון על הבמה', 'קומבינציית קומרשיאל חדה ל"Don''t Stop the Music" של Rihanna, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('7-rings-guy-ravid', 'he', 'קלינות תנועה וטיימינג מדויק', 'שגרת קומרשיאל עם טיימינג מדויק ל"7 rings" (Ariana Grande) — סטייל מסחרי לביצועים ואודישנים.'),
  ('break-free-michal-buzaglo', 'he', 'פרפורמנס וסטייל מסחרי חד', 'קומבינציית קומרשיאל חדה ל"Break Free" של Ariana Grande, שמשלבת טכניקה עם ביטחון על הבמה.'),
  ('levitating-maya-azulai', 'en', 'Grounded weight shifts and performance', 'An energetic Jazz Funk combination to "Levitating" by Dua Lipa, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('dont-start-now-tali-mizrahi', 'en', 'Groove, isolations, and movement precision', 'A rhythmic Jazz Funk routine to "Don''t Start Now" (Dua Lipa), teaching smooth weight shifts without losing energy.'),
  ('physical-yael-bar', 'en', 'Rhythm, line, and performance energy', 'An energetic Jazz Funk combination to "Physical" by Dua Lipa, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('about-damn-time-maya-azulai', 'en', 'Grounded weight shifts and performance', 'A rhythmic Jazz Funk routine to "About Damn Time" (Lizzo), teaching smooth weight shifts without losing energy.'),
  ('good-as-hell-tali-mizrahi', 'en', 'Groove, isolations, and movement precision', 'An energetic Jazz Funk combination to "Good as Hell" by Lizzo, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('flowers-yael-bar', 'en', 'Rhythm, line, and performance energy', 'A rhythmic Jazz Funk routine to "Flowers" (Miley Cyrus), teaching smooth weight shifts without losing energy.'),
  ('shirt-maya-azulai', 'en', 'Grounded weight shifts and performance', 'An energetic Jazz Funk combination to "Shirt" by SZA, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('blinding-lights-tali-mizrahi', 'en', 'Groove, isolations, and movement precision', 'A rhythmic Jazz Funk routine to "Blinding Lights" (The Weeknd), teaching smooth weight shifts without losing energy.'),
  ('need-to-know-yael-bar', 'en', 'Rhythm, line, and performance energy', 'An energetic Jazz Funk combination to "Need to Know" by Doja Cat, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('kiss-me-more-maya-azulai', 'en', 'Grounded weight shifts and performance', 'A rhythmic Jazz Funk routine to "Kiss Me More" (Doja Cat ft. SZA), teaching smooth weight shifts without losing energy.'),
  ('woman-tali-mizrahi', 'en', 'Groove, isolations, and movement precision', 'An energetic Jazz Funk combination to "Woman" by Doja Cat, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('nice-for-what-yael-bar', 'en', 'Rhythm, line, and performance energy', 'A rhythmic Jazz Funk routine to "Nice For What" (Drake), teaching smooth weight shifts without losing energy.'),
  ('as-it-was-maya-azulai', 'en', 'Grounded weight shifts and performance', 'An energetic Jazz Funk combination to "As It Was" by Harry Styles, focused on groove and performance — ideal for dancers who want to sharpen their stage expression.'),
  ('anti-hero-tali-mizrahi', 'en', 'Groove, isolations, and movement precision', 'A rhythmic Jazz Funk routine to "Anti-Hero" (Taylor Swift), teaching smooth weight shifts without losing energy.'),
  ('about-damn-time-daniel-cohen', 'en', 'Groove, polyrhythm, and floorwork', 'A powerful Hip Hop combination to "About Damn Time" by Lizzo, built on deep groove and sharp transitions.'),
  ('kill-bill-oran-ben-david', 'en', 'Systematic breakdown and coordination', 'A Hip Hop routine with a high technical emphasis to "Kill Bill" (SZA) — for dancers who want to go deeper into the style.'),
  ('creepin-amit-sharabi', 'en', 'Power, groove, and personal style', 'A powerful Hip Hop combination to "Creepin''" by Metro Boomin, The Weeknd, 21 Savage, built on deep groove and sharp transitions.'),
  ('first-class-daniel-cohen', 'en', 'Groove, polyrhythm, and floorwork', 'A Hip Hop routine with a high technical emphasis to "First Class" (Jack Harlow) — for dancers who want to go deeper into the style.'),
  ('industry-baby-oran-ben-david', 'en', 'Systematic breakdown and coordination', 'A powerful Hip Hop combination to "Industry Baby" by Lil Nas X & Jack Harlow, built on deep groove and sharp transitions.'),
  ('god-s-plan-amit-sharabi', 'en', 'Power, groove, and personal style', 'A Hip Hop routine with a high technical emphasis to "God''s Plan" (Drake) — for dancers who want to go deeper into the style.'),
  ('nice-for-what-daniel-cohen', 'en', 'Groove, polyrhythm, and floorwork', 'A powerful Hip Hop combination to "Nice For What" by Drake, built on deep groove and sharp transitions.'),
  ('savage-oran-ben-david', 'en', 'Systematic breakdown and coordination', 'A Hip Hop routine with a high technical emphasis to "Savage" (Megan Thee Stallion) — for dancers who want to go deeper into the style.'),
  ('body-amit-sharabi', 'en', 'Power, groove, and personal style', 'A powerful Hip Hop combination to "Body" by Megan Thee Stallion, built on deep groove and sharp transitions.'),
  ('get-ur-freak-on-daniel-cohen', 'en', 'Groove, polyrhythm, and floorwork', 'A Hip Hop routine with a high technical emphasis to "Get Ur Freak On" (Missy Elliott) — for dancers who want to go deeper into the style.'),
  ('work-it-oran-ben-david', 'en', 'Systematic breakdown and coordination', 'A powerful Hip Hop combination to "Work It" by Missy Elliott, built on deep groove and sharp transitions.'),
  ('sicko-mode-amit-sharabi', 'en', 'Power, groove, and personal style', 'A Hip Hop routine with a high technical emphasis to "Sicko Mode" (Travis Scott) — for dancers who want to go deeper into the style.'),
  ('humble-daniel-cohen', 'en', 'Groove, polyrhythm, and floorwork', 'A powerful Hip Hop combination to "Humble" by Kendrick Lamar, built on deep groove and sharp transitions.'),
  ('dna-oran-ben-david', 'en', 'Systematic breakdown and coordination', 'A Hip Hop routine with a high technical emphasis to "DNA" (Kendrick Lamar) — for dancers who want to go deeper into the style.'),
  ('kill-bill-noa-sagi', 'en', 'Line, heel control, and performance', 'A seductive, confident Heels combination to "Kill Bill" by SZA, teaching heel control without sacrificing technique.'),
  ('snooze-maya-rozin', 'en', 'Posture, confidence, and heel mobility', 'A Heels routine with an emphasis on posture, line, and performance, to "Snooze" (SZA).'),
  ('shirt-noga-eliyahu', 'en', 'Grace and control on stage', 'A seductive, confident Heels combination to "Shirt" by SZA, teaching heel control without sacrificing technique.'),
  ('earned-it-noa-sagi', 'en', 'Line, heel control, and performance', 'A Heels routine with an emphasis on posture, line, and performance, to "Earned It" (The Weeknd).'),
  ('die-for-you-maya-rozin', 'en', 'Posture, confidence, and heel mobility', 'A seductive, confident Heels combination to "Die For You" by The Weeknd, teaching heel control without sacrificing technique.'),
  ('creepin-noga-eliyahu', 'en', 'Grace and control on stage', 'A Heels routine with an emphasis on posture, line, and performance, to "Creepin''" (Metro Boomin, The Weeknd, 21 Savage).'),
  ('need-to-know-noa-sagi', 'en', 'Line, heel control, and performance', 'A seductive, confident Heels combination to "Need to Know" by Doja Cat, teaching heel control without sacrificing technique.'),
  ('kiss-me-more-maya-rozin', 'en', 'Posture, confidence, and heel mobility', 'A Heels routine with an emphasis on posture, line, and performance, to "Kiss Me More" (Doja Cat ft. SZA).'),
  ('body-party-noga-eliyahu', 'en', 'Grace and control on stage', 'A seductive, confident Heels combination to "Body Party" by Ciara, teaching heel control without sacrificing technique.'),
  ('ride-noa-sagi', 'en', 'Line, heel control, and performance', 'A Heels routine with an emphasis on posture, line, and performance, to "Ride" (Ciara).'),
  ('2-on-maya-rozin', 'en', 'Posture, confidence, and heel mobility', 'A seductive, confident Heels combination to "2 On" by Tinashe, teaching heel control without sacrificing technique.'),
  ('distraction-noga-eliyahu', 'en', 'Grace and control on stage', 'A Heels routine with an emphasis on posture, line, and performance, to "Distraction" (Kehlani).'),
  ('me-and-u-noa-sagi', 'en', 'Line, heel control, and performance', 'A seductive, confident Heels combination to "Me & U" by Cassie, teaching heel control without sacrificing technique.'),
  ('rock-the-boat-maya-rozin', 'en', 'Posture, confidence, and heel mobility', 'A Heels routine with an emphasis on posture, line, and performance, to "Rock the Boat" (Aaliyah).'),
  ('easy-on-me-yasmin-kadosh', 'en', 'Technique, line, and emotional depth', 'A lyrical Jazz combination to "Easy On Me" by Adele, with an emphasis on emotional depth and musicality.'),
  ('rolling-in-the-deep-omer-tzur', 'en', 'Musicality and body control', 'A technical Jazz routine to "Rolling in the Deep" (Adele) — for dancers who want to sharpen line and physical expression.'),
  ('stay-with-me-hila-ben-ari', 'en', 'Lyricism and performance', 'A lyrical Jazz combination to "Stay With Me" by Sam Smith, with an emphasis on emotional depth and musicality.'),
  ('unholy-yasmin-kadosh', 'en', 'Technique, line, and emotional depth', 'A technical Jazz routine to "Unholy" (Sam Smith ft. Kim Petras) — for dancers who want to sharpen line and physical expression.'),
  ('ocean-eyes-omer-tzur', 'en', 'Musicality and body control', 'A lyrical Jazz combination to "Ocean Eyes" by Billie Eilish, with an emphasis on emotional depth and musicality.'),
  ('happier-than-ever-hila-ben-ari', 'en', 'Lyricism and performance', 'A technical Jazz routine to "Happier Than Ever" (Billie Eilish) — for dancers who want to sharpen line and physical expression.'),
  ('best-part-yasmin-kadosh', 'en', 'Technique, line, and emotional depth', 'A lyrical Jazz combination to "Best Part" by H.E.R. ft. Daniel Caesar, with an emphasis on emotional depth and musicality.'),
  ('someone-you-loved-omer-tzur', 'en', 'Musicality and body control', 'A technical Jazz routine to "Someone You Loved" (Lewis Capaldi) — for dancers who want to sharpen line and physical expression.'),
  ('my-hair-hila-ben-ari', 'en', 'Lyricism and performance', 'A lyrical Jazz combination to "my hair" by Ariana Grande, with an emphasis on emotional depth and musicality.'),
  ('be-honest-yasmin-kadosh', 'en', 'Technique, line, and emotional depth', 'A technical Jazz routine to "Be Honest" (Jorja Smith) — for dancers who want to sharpen line and physical expression.'),
  ('if-i-aint-got-you-omer-tzur', 'en', 'Musicality and body control', 'A lyrical Jazz combination to "If I Ain''t Got You" by Alicia Keys, with an emphasis on emotional depth and musicality.'),
  ('all-of-me-hila-ben-ari', 'en', 'Lyricism and performance', 'A technical Jazz routine to "All of Me" (John Legend) — for dancers who want to sharpen line and physical expression.'),
  ('get-you-yasmin-kadosh', 'en', 'Technique, line, and emotional depth', 'A lyrical Jazz combination to "Get You" by Daniel Caesar ft. Kali Uchis, with an emphasis on emotional depth and musicality.'),
  ('toronto-omer-tzur', 'en', 'Musicality and body control', 'A technical Jazz routine to "Toronto" (Snoh Aalegra) — for dancers who want to sharpen line and physical expression.'),
  ('be-honest-efrat-wolde', 'en', 'Isolations, groove, and group energy', 'A rhythmic Afro combination to "Be Honest" by Jorja Smith, with an emphasis on isolations and group energy.'),
  ('higher-yonatan-tesfaye', 'en', 'Authentic African rhythm and free movement', 'A joyful Afro routine to "Higher" (Tems) — authentic African rhythm and free movement.'),
  ('last-last-efrat-wolde', 'en', 'Sending energy and movement joy', 'A rhythmic Afro combination to "Last Last" by Burna Boy, with an emphasis on isolations and group energy.'),
  ('kilometre-yonatan-tesfaye', 'en', 'Isolations, groove, and group energy', 'A joyful Afro routine to "Kilometre" (Burna Boy) — authentic African rhythm and free movement.'),
  ('essence-efrat-wolde', 'en', 'Authentic African rhythm and free movement', 'A rhythmic Afro combination to "Essence" by Wizkid ft. Tems, with an emphasis on isolations and group energy.'),
  ('ojuelegba-yonatan-tesfaye', 'en', 'Sending energy and movement joy', 'A joyful Afro routine to "Ojuelegba" (Wizkid) — authentic African rhythm and free movement.'),
  ('fall-efrat-wolde', 'en', 'Isolations, groove, and group energy', 'A rhythmic Afro combination to "Fall" by Davido, with an emphasis on isolations and group energy.'),
  ('unavailable-yonatan-tesfaye', 'en', 'Authentic African rhythm and free movement', 'A joyful Afro routine to "Unavailable" (Davido ft. Musa Keys) — authentic African rhythm and free movement.'),
  ('calm-down-efrat-wolde', 'en', 'Sending energy and movement joy', 'A rhythmic Afro combination to "Calm Down" by Rema, with an emphasis on isolations and group energy.'),
  ('dumebi-yonatan-tesfaye', 'en', 'Isolations, groove, and group energy', 'A joyful Afro routine to "Dumebi" (Rema) — authentic African rhythm and free movement.'),
  ('love-nwantiti-efrat-wolde', 'en', 'Authentic African rhythm and free movement', 'A rhythmic Afro combination to "Love Nwantiti" by CKay, with an emphasis on isolations and group energy.'),
  ('free-mind-yonatan-tesfaye', 'en', 'Sending energy and movement joy', 'A joyful Afro routine to "Free Mind" (Tems) — authentic African rhythm and free movement.'),
  ('peru-efrat-wolde', 'en', 'Isolations, groove, and group energy', 'A rhythmic Afro combination to "Peru" by Fireboy DML, with an emphasis on isolations and group energy.'),
  ('rush-yonatan-tesfaye', 'en', 'Authentic African rhythm and free movement', 'A joyful Afro routine to "Rush" (Ayra Starr) — authentic African rhythm and free movement.'),
  ('terminator-or-katz', 'en', 'Bounce, groove, and attitude', 'A bouncy, attitude-filled Dancehall combination to "Terminator" by Asake, for dancers who want real street style.'),
  ('touch-it-tamir-levy', 'en', 'Power and precision in footwork', 'A high-energy Dancehall routine to "Touch It" (KiDi) — power and precision in the footwork.'),
  ('temperature-or-katz', 'en', 'High energy and street style', 'A bouncy, attitude-filled Dancehall combination to "Temperature" by Sean Paul, for dancers who want real street style.'),
  ('get-busy-tamir-levy', 'en', 'Bounce, groove, and attitude', 'A high-energy Dancehall routine to "Get Busy" (Sean Paul) — power and precision in the footwork.'),
  ('family-or-katz', 'en', 'Power and precision in footwork', 'A bouncy, attitude-filled Dancehall combination to "Family" by Popcaan, for dancers who want real street style.'),
  ('ova-dweet-tamir-levy', 'en', 'High energy and street style', 'A high-energy Dancehall routine to "Ova Dweet" (Popcaan) — power and precision in the footwork.'),
  ('blessed-or-katz', 'en', 'Bounce, groove, and attitude', 'A bouncy, attitude-filled Dancehall combination to "Blessed" by Shenseea, for dancers who want real street style.'),
  ('lick-tamir-levy', 'en', 'Power and precision in footwork', 'A high-energy Dancehall routine to "Lick" (Shenseea) — power and precision in the footwork.'),
  ('bruk-off-yuh-back-or-katz', 'en', 'High energy and street style', 'A bouncy, attitude-filled Dancehall combination to "Bruk Off Yuh Back" by Konshens, for dancers who want real street style.'),
  ('fever-tamir-levy', 'en', 'Bounce, groove, and attitude', 'A high-energy Dancehall routine to "Fever" (Vybz Kartel) — power and precision in the footwork.'),
  ('so-mi-like-it-or-katz', 'en', 'Power and precision in footwork', 'A bouncy, attitude-filled Dancehall combination to "So Mi Like It" by Spice, for dancers who want real street style.'),
  ('coke-tamir-levy', 'en', 'High energy and street style', 'A high-energy Dancehall routine to "Coke" (Skillibeng) — power and precision in the footwork.'),
  ('ina-real-life-or-katz', 'en', 'Bounce, groove, and attitude', 'A bouncy, attitude-filled Dancehall combination to "Ina Real Life" by Alkaline, for dancers who want real street style.'),
  ('owe-me-nothing-tamir-levy', 'en', 'Power and precision in footwork', 'A high-energy Dancehall routine to "Owe Me Nothing" (Dexta Daps) — power and precision in the footwork.'),
  ('cant-stop-the-feeling-michal-buzaglo', 'en', 'Sharp performance and commercial style', 'A sharp Commercial combination to "Can''t Stop the Feeling" by Justin Timberlake, blending technique with stage confidence.'),
  ('unholy-guy-ravid', 'en', 'Blending technique with stage confidence', 'A Commercial routine with precise timing to "Unholy" (Sam Smith ft. Kim Petras) — commercial style for gigs and auditions.'),
  ('unavailable-michal-buzaglo', 'en', 'Clean movement and precise timing', 'A sharp Commercial combination to "Unavailable" by Davido ft. Musa Keys, blending technique with stage confidence.'),
  ('calm-down-guy-ravid', 'en', 'Sharp performance and commercial style', 'A Commercial routine with precise timing to "Calm Down" (Rema) — commercial style for gigs and auditions.'),
  ('rush-michal-buzaglo', 'en', 'Blending technique with stage confidence', 'A sharp Commercial combination to "Rush" by Ayra Starr, blending technique with stage confidence.'),
  ('sad-girlz-luv-money-guy-ravid', 'en', 'Clean movement and precise timing', 'A Commercial routine with precise timing to "Sad Girlz Luv Money" (Amaarae) — commercial style for gigs and auditions.'),
  ('blessed-michal-buzaglo', 'en', 'Sharp performance and commercial style', 'A sharp Commercial combination to "Blessed" by Shenseea, blending technique with stage confidence.'),
  ('break-my-soul-guy-ravid', 'en', 'Blending technique with stage confidence', 'A Commercial routine with precise timing to "Break My Soul" (Beyoncé) — commercial style for gigs and auditions.'),
  ('formation-michal-buzaglo', 'en', 'Clean movement and precise timing', 'A sharp Commercial combination to "Formation" by Beyoncé, blending technique with stage confidence.'),
  ('umbrella-guy-ravid', 'en', 'Sharp performance and commercial style', 'A Commercial routine with precise timing to "Umbrella" (Rihanna) — commercial style for gigs and auditions.'),
  ('dont-stop-the-music-michal-buzaglo', 'en', 'Blending technique with stage confidence', 'A sharp Commercial combination to "Don''t Stop the Music" by Rihanna, blending technique with stage confidence.'),
  ('7-rings-guy-ravid', 'en', 'Clean movement and precise timing', 'A Commercial routine with precise timing to "7 rings" (Ariana Grande) — commercial style for gigs and auditions.'),
  ('break-free-michal-buzaglo', 'en', 'Sharp performance and commercial style', 'A sharp Commercial combination to "Break Free" by Ariana Grande, blending technique with stage confidence.');

INSERT INTO routine_chapters (routine_slug, chapter_id, time_seconds, sort_order) VALUES
  ('levitating-maya-azulai', 'full-performance', 0, 0),
  ('levitating-maya-azulai', 'breakdown', 24, 1),
  ('levitating-maya-azulai', 'slow-practice', 65, 2),
  ('levitating-maya-azulai', 'full-speed', 118, 3),
  ('dont-start-now-tali-mizrahi', 'full-performance', 0, 0),
  ('dont-start-now-tali-mizrahi', 'breakdown', 22, 1),
  ('dont-start-now-tali-mizrahi', 'slow-practice', 59, 2),
  ('dont-start-now-tali-mizrahi', 'full-speed', 106, 3),
  ('physical-yael-bar', 'full-performance', 0, 0),
  ('physical-yael-bar', 'breakdown', 23, 1),
  ('physical-yael-bar', 'slow-practice', 62, 2),
  ('physical-yael-bar', 'full-speed', 112, 3),
  ('about-damn-time-maya-azulai', 'full-performance', 0, 0),
  ('about-damn-time-maya-azulai', 'breakdown', 23, 1),
  ('about-damn-time-maya-azulai', 'slow-practice', 61, 2),
  ('about-damn-time-maya-azulai', 'full-speed', 111, 3),
  ('good-as-hell-tali-mizrahi', 'full-performance', 0, 0),
  ('good-as-hell-tali-mizrahi', 'breakdown', 19, 1),
  ('good-as-hell-tali-mizrahi', 'slow-practice', 51, 2),
  ('good-as-hell-tali-mizrahi', 'full-speed', 92, 3),
  ('flowers-yael-bar', 'full-performance', 0, 0),
  ('flowers-yael-bar', 'breakdown', 24, 1),
  ('flowers-yael-bar', 'slow-practice', 64, 2),
  ('flowers-yael-bar', 'full-speed', 116, 3),
  ('shirt-maya-azulai', 'full-performance', 0, 0),
  ('shirt-maya-azulai', 'breakdown', 22, 1),
  ('shirt-maya-azulai', 'slow-practice', 58, 2),
  ('shirt-maya-azulai', 'full-speed', 105, 3),
  ('blinding-lights-tali-mizrahi', 'full-performance', 0, 0),
  ('blinding-lights-tali-mizrahi', 'breakdown', 24, 1),
  ('blinding-lights-tali-mizrahi', 'slow-practice', 64, 2),
  ('blinding-lights-tali-mizrahi', 'full-speed', 116, 3),
  ('need-to-know-yael-bar', 'full-performance', 0, 0),
  ('need-to-know-yael-bar', 'breakdown', 25, 1),
  ('need-to-know-yael-bar', 'slow-practice', 67, 2),
  ('need-to-know-yael-bar', 'full-speed', 122, 3),
  ('kiss-me-more-maya-azulai', 'full-performance', 0, 0),
  ('kiss-me-more-maya-azulai', 'breakdown', 25, 1),
  ('kiss-me-more-maya-azulai', 'slow-practice', 67, 2),
  ('kiss-me-more-maya-azulai', 'full-speed', 121, 3),
  ('woman-tali-mizrahi', 'full-performance', 0, 0),
  ('woman-tali-mizrahi', 'breakdown', 21, 1),
  ('woman-tali-mizrahi', 'slow-practice', 55, 2),
  ('woman-tali-mizrahi', 'full-speed', 100, 3),
  ('nice-for-what-yael-bar', 'full-performance', 0, 0),
  ('nice-for-what-yael-bar', 'breakdown', 25, 1),
  ('nice-for-what-yael-bar', 'slow-practice', 67, 2),
  ('nice-for-what-yael-bar', 'full-speed', 122, 3),
  ('as-it-was-maya-azulai', 'full-performance', 0, 0),
  ('as-it-was-maya-azulai', 'breakdown', 20, 1),
  ('as-it-was-maya-azulai', 'slow-practice', 53, 2),
  ('as-it-was-maya-azulai', 'full-speed', 97, 3),
  ('anti-hero-tali-mizrahi', 'full-performance', 0, 0),
  ('anti-hero-tali-mizrahi', 'breakdown', 24, 1),
  ('anti-hero-tali-mizrahi', 'slow-practice', 64, 2),
  ('anti-hero-tali-mizrahi', 'full-speed', 116, 3),
  ('about-damn-time-daniel-cohen', 'full-performance', 0, 0),
  ('about-damn-time-daniel-cohen', 'breakdown', 23, 1),
  ('about-damn-time-daniel-cohen', 'slow-practice', 61, 2),
  ('about-damn-time-daniel-cohen', 'full-speed', 111, 3),
  ('kill-bill-oran-ben-david', 'full-performance', 0, 0),
  ('kill-bill-oran-ben-david', 'breakdown', 18, 1),
  ('kill-bill-oran-ben-david', 'slow-practice', 49, 2),
  ('kill-bill-oran-ben-david', 'full-speed', 89, 3),
  ('creepin-amit-sharabi', 'full-performance', 0, 0),
  ('creepin-amit-sharabi', 'breakdown', 27, 1),
  ('creepin-amit-sharabi', 'slow-practice', 71, 2),
  ('creepin-amit-sharabi', 'full-speed', 128, 3),
  ('first-class-daniel-cohen', 'full-performance', 0, 0),
  ('first-class-daniel-cohen', 'breakdown', 21, 1),
  ('first-class-daniel-cohen', 'slow-practice', 55, 2),
  ('first-class-daniel-cohen', 'full-speed', 100, 3),
  ('industry-baby-oran-ben-david', 'full-performance', 0, 0),
  ('industry-baby-oran-ben-david', 'breakdown', 25, 1),
  ('industry-baby-oran-ben-david', 'slow-practice', 68, 2),
  ('industry-baby-oran-ben-david', 'full-speed', 123, 3),
  ('god-s-plan-amit-sharabi', 'full-performance', 0, 0),
  ('god-s-plan-amit-sharabi', 'breakdown', 24, 1),
  ('god-s-plan-amit-sharabi', 'slow-practice', 63, 2),
  ('god-s-plan-amit-sharabi', 'full-speed', 115, 3),
  ('nice-for-what-daniel-cohen', 'full-performance', 0, 0),
  ('nice-for-what-daniel-cohen', 'breakdown', 25, 1),
  ('nice-for-what-daniel-cohen', 'slow-practice', 67, 2),
  ('nice-for-what-daniel-cohen', 'full-speed', 122, 3),
  ('savage-oran-ben-david', 'full-performance', 0, 0),
  ('savage-oran-ben-david', 'breakdown', 19, 1),
  ('savage-oran-ben-david', 'slow-practice', 50, 2),
  ('savage-oran-ben-david', 'full-speed', 90, 3),
  ('body-amit-sharabi', 'full-performance', 0, 0),
  ('body-amit-sharabi', 'breakdown', 21, 1),
  ('body-amit-sharabi', 'slow-practice', 55, 2),
  ('body-amit-sharabi', 'full-speed', 99, 3),
  ('get-ur-freak-on-daniel-cohen', 'full-performance', 0, 0),
  ('get-ur-freak-on-daniel-cohen', 'breakdown', 28, 1),
  ('get-ur-freak-on-daniel-cohen', 'slow-practice', 75, 2),
  ('get-ur-freak-on-daniel-cohen', 'full-speed', 135, 3),
  ('work-it-oran-ben-david', 'full-performance', 0, 0),
  ('work-it-oran-ben-david', 'breakdown', 24, 1),
  ('work-it-oran-ben-david', 'slow-practice', 65, 2),
  ('work-it-oran-ben-david', 'full-speed', 118, 3),
  ('sicko-mode-amit-sharabi', 'full-performance', 0, 0),
  ('sicko-mode-amit-sharabi', 'breakdown', 37, 1),
  ('sicko-mode-amit-sharabi', 'slow-practice', 100, 2),
  ('sicko-mode-amit-sharabi', 'full-speed', 181, 3),
  ('humble-daniel-cohen', 'full-performance', 0, 0),
  ('humble-daniel-cohen', 'breakdown', 21, 1),
  ('humble-daniel-cohen', 'slow-practice', 57, 2),
  ('humble-daniel-cohen', 'full-speed', 103, 3),
  ('dna-oran-ben-david', 'full-performance', 0, 0),
  ('dna-oran-ben-david', 'breakdown', 22, 1),
  ('dna-oran-ben-david', 'slow-practice', 59, 2),
  ('dna-oran-ben-david', 'full-speed', 107, 3),
  ('kill-bill-noa-sagi', 'full-performance', 0, 0),
  ('kill-bill-noa-sagi', 'breakdown', 18, 1),
  ('kill-bill-noa-sagi', 'slow-practice', 49, 2),
  ('kill-bill-noa-sagi', 'full-speed', 89, 3),
  ('snooze-maya-rozin', 'full-performance', 0, 0),
  ('snooze-maya-rozin', 'breakdown', 24, 1),
  ('snooze-maya-rozin', 'slow-practice', 64, 2),
  ('snooze-maya-rozin', 'full-speed', 117, 3),
  ('shirt-noga-eliyahu', 'full-performance', 0, 0),
  ('shirt-noga-eliyahu', 'breakdown', 22, 1),
  ('shirt-noga-eliyahu', 'slow-practice', 58, 2),
  ('shirt-noga-eliyahu', 'full-speed', 105, 3),
  ('earned-it-noa-sagi', 'full-performance', 0, 0),
  ('earned-it-noa-sagi', 'breakdown', 30, 1),
  ('earned-it-noa-sagi', 'slow-practice', 80, 2),
  ('earned-it-noa-sagi', 'full-speed', 145, 3),
  ('die-for-you-maya-rozin', 'full-performance', 0, 0),
  ('die-for-you-maya-rozin', 'breakdown', 31, 1),
  ('die-for-you-maya-rozin', 'slow-practice', 83, 2),
  ('die-for-you-maya-rozin', 'full-speed', 151, 3),
  ('creepin-noga-eliyahu', 'full-performance', 0, 0),
  ('creepin-noga-eliyahu', 'breakdown', 27, 1),
  ('creepin-noga-eliyahu', 'slow-practice', 71, 2),
  ('creepin-noga-eliyahu', 'full-speed', 128, 3),
  ('need-to-know-noa-sagi', 'full-performance', 0, 0),
  ('need-to-know-noa-sagi', 'breakdown', 25, 1),
  ('need-to-know-noa-sagi', 'slow-practice', 67, 2),
  ('need-to-know-noa-sagi', 'full-speed', 122, 3),
  ('kiss-me-more-maya-rozin', 'full-performance', 0, 0),
  ('kiss-me-more-maya-rozin', 'breakdown', 25, 1),
  ('kiss-me-more-maya-rozin', 'slow-practice', 67, 2),
  ('kiss-me-more-maya-rozin', 'full-speed', 121, 3),
  ('body-party-noga-eliyahu', 'full-performance', 0, 0),
  ('body-party-noga-eliyahu', 'breakdown', 29, 1),
  ('body-party-noga-eliyahu', 'slow-practice', 77, 2),
  ('body-party-noga-eliyahu', 'full-speed', 139, 3),
  ('ride-noa-sagi', 'full-performance', 0, 0),
  ('ride-noa-sagi', 'breakdown', 33, 1),
  ('ride-noa-sagi', 'slow-practice', 88, 2),
  ('ride-noa-sagi', 'full-speed', 160, 3),
  ('2-on-maya-rozin', 'full-performance', 0, 0),
  ('2-on-maya-rozin', 'breakdown', 26, 1),
  ('2-on-maya-rozin', 'slow-practice', 68, 2),
  ('2-on-maya-rozin', 'full-speed', 124, 3),
  ('distraction-noga-eliyahu', 'full-performance', 0, 0),
  ('distraction-noga-eliyahu', 'breakdown', 24, 1),
  ('distraction-noga-eliyahu', 'slow-practice', 63, 2),
  ('distraction-noga-eliyahu', 'full-speed', 114, 3),
  ('me-and-u-noa-sagi', 'full-performance', 0, 0),
  ('me-and-u-noa-sagi', 'breakdown', 26, 1),
  ('me-and-u-noa-sagi', 'slow-practice', 68, 2),
  ('me-and-u-noa-sagi', 'full-speed', 124, 3),
  ('rock-the-boat-maya-rozin', 'full-performance', 0, 0),
  ('rock-the-boat-maya-rozin', 'breakdown', 29, 1),
  ('rock-the-boat-maya-rozin', 'slow-practice', 78, 2),
  ('rock-the-boat-maya-rozin', 'full-speed', 142, 3),
  ('easy-on-me-yasmin-kadosh', 'full-performance', 0, 0),
  ('easy-on-me-yasmin-kadosh', 'breakdown', 27, 1),
  ('easy-on-me-yasmin-kadosh', 'slow-practice', 72, 2),
  ('easy-on-me-yasmin-kadosh', 'full-speed', 130, 3),
  ('rolling-in-the-deep-omer-tzur', 'full-performance', 0, 0),
  ('rolling-in-the-deep-omer-tzur', 'breakdown', 27, 1),
  ('rolling-in-the-deep-omer-tzur', 'slow-practice', 73, 2),
  ('rolling-in-the-deep-omer-tzur', 'full-speed', 132, 3),
  ('stay-with-me-hila-ben-ari', 'full-performance', 0, 0),
  ('stay-with-me-hila-ben-ari', 'breakdown', 21, 1),
  ('stay-with-me-hila-ben-ari', 'slow-practice', 55, 2),
  ('stay-with-me-hila-ben-ari', 'full-speed', 100, 3),
  ('unholy-yasmin-kadosh', 'full-performance', 0, 0),
  ('unholy-yasmin-kadosh', 'breakdown', 19, 1),
  ('unholy-yasmin-kadosh', 'slow-practice', 50, 2),
  ('unholy-yasmin-kadosh', 'full-speed', 90, 3),
  ('ocean-eyes-omer-tzur', 'full-performance', 0, 0),
  ('ocean-eyes-omer-tzur', 'breakdown', 24, 1),
  ('ocean-eyes-omer-tzur', 'slow-practice', 64, 2),
  ('ocean-eyes-omer-tzur', 'full-speed', 116, 3),
  ('happier-than-ever-hila-ben-ari', 'full-performance', 0, 0),
  ('happier-than-ever-hila-ben-ari', 'breakdown', 36, 1),
  ('happier-than-ever-hila-ben-ari', 'slow-practice', 95, 2),
  ('happier-than-ever-hila-ben-ari', 'full-speed', 173, 3),
  ('best-part-yasmin-kadosh', 'full-performance', 0, 0),
  ('best-part-yasmin-kadosh', 'breakdown', 25, 1),
  ('best-part-yasmin-kadosh', 'slow-practice', 67, 2),
  ('best-part-yasmin-kadosh', 'full-speed', 121, 3),
  ('someone-you-loved-omer-tzur', 'full-performance', 0, 0),
  ('someone-you-loved-omer-tzur', 'breakdown', 22, 1),
  ('someone-you-loved-omer-tzur', 'slow-practice', 58, 2),
  ('someone-you-loved-omer-tzur', 'full-speed', 106, 3),
  ('my-hair-hila-ben-ari', 'full-performance', 0, 0),
  ('my-hair-hila-ben-ari', 'breakdown', 19, 1),
  ('my-hair-hila-ben-ari', 'slow-practice', 52, 2),
  ('my-hair-hila-ben-ari', 'full-speed', 93, 3),
  ('be-honest-yasmin-kadosh', 'full-performance', 0, 0),
  ('be-honest-yasmin-kadosh', 'breakdown', 25, 1),
  ('be-honest-yasmin-kadosh', 'slow-practice', 67, 2),
  ('be-honest-yasmin-kadosh', 'full-speed', 121, 3),
  ('if-i-aint-got-you-omer-tzur', 'full-performance', 0, 0),
  ('if-i-aint-got-you-omer-tzur', 'breakdown', 27, 1),
  ('if-i-aint-got-you-omer-tzur', 'slow-practice', 73, 2),
  ('if-i-aint-got-you-omer-tzur', 'full-speed', 132, 3),
  ('all-of-me-hila-ben-ari', 'full-performance', 0, 0),
  ('all-of-me-hila-ben-ari', 'breakdown', 32, 1),
  ('all-of-me-hila-ben-ari', 'slow-practice', 86, 2),
  ('all-of-me-hila-ben-ari', 'full-speed', 156, 3),
  ('get-you-yasmin-kadosh', 'full-performance', 0, 0),
  ('get-you-yasmin-kadosh', 'breakdown', 30, 1),
  ('get-you-yasmin-kadosh', 'slow-practice', 79, 2),
  ('get-you-yasmin-kadosh', 'full-speed', 144, 3),
  ('toronto-omer-tzur', 'full-performance', 0, 0),
  ('toronto-omer-tzur', 'breakdown', 22, 1),
  ('toronto-omer-tzur', 'slow-practice', 60, 2),
  ('toronto-omer-tzur', 'full-speed', 108, 3),
  ('be-honest-efrat-wolde', 'full-performance', 0, 0),
  ('be-honest-efrat-wolde', 'breakdown', 25, 1),
  ('be-honest-efrat-wolde', 'slow-practice', 67, 2),
  ('be-honest-efrat-wolde', 'full-speed', 121, 3),
  ('higher-yonatan-tesfaye', 'full-performance', 0, 0),
  ('higher-yonatan-tesfaye', 'breakdown', 23, 1),
  ('higher-yonatan-tesfaye', 'slow-practice', 62, 2),
  ('higher-yonatan-tesfaye', 'full-speed', 113, 3),
  ('last-last-efrat-wolde', 'full-performance', 0, 0),
  ('last-last-efrat-wolde', 'breakdown', 23, 1),
  ('last-last-efrat-wolde', 'slow-practice', 62, 2),
  ('last-last-efrat-wolde', 'full-speed', 113, 3),
  ('kilometre-yonatan-tesfaye', 'full-performance', 0, 0),
  ('kilometre-yonatan-tesfaye', 'breakdown', 26, 1),
  ('kilometre-yonatan-tesfaye', 'slow-practice', 68, 2),
  ('kilometre-yonatan-tesfaye', 'full-speed', 124, 3),
  ('essence-efrat-wolde', 'full-performance', 0, 0),
  ('essence-efrat-wolde', 'breakdown', 30, 1),
  ('essence-efrat-wolde', 'slow-practice', 79, 2),
  ('essence-efrat-wolde', 'full-speed', 144, 3),
  ('ojuelegba-yonatan-tesfaye', 'full-performance', 0, 0),
  ('ojuelegba-yonatan-tesfaye', 'breakdown', 27, 1),
  ('ojuelegba-yonatan-tesfaye', 'slow-practice', 73, 2),
  ('ojuelegba-yonatan-tesfaye', 'full-speed', 132, 3),
  ('fall-efrat-wolde', 'full-performance', 0, 0),
  ('fall-efrat-wolde', 'breakdown', 30, 1),
  ('fall-efrat-wolde', 'slow-practice', 79, 2),
  ('fall-efrat-wolde', 'full-speed', 143, 3),
  ('unavailable-yonatan-tesfaye', 'full-performance', 0, 0),
  ('unavailable-yonatan-tesfaye', 'breakdown', 21, 1),
  ('unavailable-yonatan-tesfaye', 'slow-practice', 57, 2),
  ('unavailable-yonatan-tesfaye', 'full-speed', 103, 3),
  ('calm-down-efrat-wolde', 'full-performance', 0, 0),
  ('calm-down-efrat-wolde', 'breakdown', 26, 1),
  ('calm-down-efrat-wolde', 'slow-practice', 70, 2),
  ('calm-down-efrat-wolde', 'full-speed', 127, 3),
  ('dumebi-yonatan-tesfaye', 'full-performance', 0, 0),
  ('dumebi-yonatan-tesfaye', 'breakdown', 24, 1),
  ('dumebi-yonatan-tesfaye', 'slow-practice', 63, 2),
  ('dumebi-yonatan-tesfaye', 'full-speed', 114, 3),
  ('love-nwantiti-efrat-wolde', 'full-performance', 0, 0),
  ('love-nwantiti-efrat-wolde', 'breakdown', 20, 1),
  ('love-nwantiti-efrat-wolde', 'slow-practice', 53, 2),
  ('love-nwantiti-efrat-wolde', 'full-speed', 97, 3),
  ('free-mind-yonatan-tesfaye', 'full-performance', 0, 0),
  ('free-mind-yonatan-tesfaye', 'breakdown', 27, 1),
  ('free-mind-yonatan-tesfaye', 'slow-practice', 73, 2),
  ('free-mind-yonatan-tesfaye', 'full-speed', 132, 3),
  ('peru-efrat-wolde', 'full-performance', 0, 0),
  ('peru-efrat-wolde', 'breakdown', 21, 1),
  ('peru-efrat-wolde', 'slow-practice', 55, 2),
  ('peru-efrat-wolde', 'full-speed', 100, 3),
  ('rush-yonatan-tesfaye', 'full-performance', 0, 0),
  ('rush-yonatan-tesfaye', 'breakdown', 20, 1),
  ('rush-yonatan-tesfaye', 'slow-practice', 54, 2),
  ('rush-yonatan-tesfaye', 'full-speed', 99, 3),
  ('terminator-or-katz', 'full-performance', 0, 0),
  ('terminator-or-katz', 'breakdown', 21, 1),
  ('terminator-or-katz', 'slow-practice', 55, 2),
  ('terminator-or-katz', 'full-speed', 100, 3),
  ('touch-it-tamir-levy', 'full-performance', 0, 0),
  ('touch-it-tamir-levy', 'breakdown', 24, 1),
  ('touch-it-tamir-levy', 'slow-practice', 64, 2),
  ('touch-it-tamir-levy', 'full-speed', 116, 3),
  ('temperature-or-katz', 'full-performance', 0, 0),
  ('temperature-or-katz', 'breakdown', 24, 1),
  ('temperature-or-katz', 'slow-practice', 65, 2),
  ('temperature-or-katz', 'full-speed', 118, 3),
  ('get-busy-tamir-levy', 'full-performance', 0, 0),
  ('get-busy-tamir-levy', 'breakdown', 26, 1),
  ('get-busy-tamir-levy', 'slow-practice', 69, 2),
  ('get-busy-tamir-levy', 'full-speed', 125, 3),
  ('family-or-katz', 'full-performance', 0, 0),
  ('family-or-katz', 'breakdown', 24, 1),
  ('family-or-katz', 'slow-practice', 64, 2),
  ('family-or-katz', 'full-speed', 116, 3),
  ('ova-dweet-tamir-levy', 'full-performance', 0, 0),
  ('ova-dweet-tamir-levy', 'breakdown', 23, 1),
  ('ova-dweet-tamir-levy', 'slow-practice', 61, 2),
  ('ova-dweet-tamir-levy', 'full-speed', 111, 3),
  ('blessed-or-katz', 'full-performance', 0, 0),
  ('blessed-or-katz', 'breakdown', 22, 1),
  ('blessed-or-katz', 'slow-practice', 59, 2),
  ('blessed-or-katz', 'full-speed', 106, 3),
  ('lick-tamir-levy', 'full-performance', 0, 0),
  ('lick-tamir-levy', 'breakdown', 22, 1),
  ('lick-tamir-levy', 'slow-practice', 60, 2),
  ('lick-tamir-levy', 'full-speed', 108, 3),
  ('bruk-off-yuh-back-or-katz', 'full-performance', 0, 0),
  ('bruk-off-yuh-back-or-katz', 'breakdown', 22, 1),
  ('bruk-off-yuh-back-or-katz', 'slow-practice', 59, 2),
  ('bruk-off-yuh-back-or-katz', 'full-speed', 107, 3),
  ('fever-tamir-levy', 'full-performance', 0, 0),
  ('fever-tamir-levy', 'breakdown', 23, 1),
  ('fever-tamir-levy', 'slow-practice', 61, 2),
  ('fever-tamir-levy', 'full-speed', 111, 3),
  ('so-mi-like-it-or-katz', 'full-performance', 0, 0),
  ('so-mi-like-it-or-katz', 'breakdown', 21, 1),
  ('so-mi-like-it-or-katz', 'slow-practice', 57, 2),
  ('so-mi-like-it-or-katz', 'full-speed', 103, 3),
  ('coke-tamir-levy', 'full-performance', 0, 0),
  ('coke-tamir-levy', 'breakdown', 19, 1),
  ('coke-tamir-levy', 'slow-practice', 51, 2),
  ('coke-tamir-levy', 'full-speed', 93, 3),
  ('ina-real-life-or-katz', 'full-performance', 0, 0),
  ('ina-real-life-or-katz', 'breakdown', 23, 1),
  ('ina-real-life-or-katz', 'slow-practice', 61, 2),
  ('ina-real-life-or-katz', 'full-speed', 110, 3),
  ('owe-me-nothing-tamir-levy', 'full-performance', 0, 0),
  ('owe-me-nothing-tamir-levy', 'breakdown', 26, 1),
  ('owe-me-nothing-tamir-levy', 'slow-practice', 69, 2),
  ('owe-me-nothing-tamir-levy', 'full-speed', 125, 3),
  ('cant-stop-the-feeling-michal-buzaglo', 'full-performance', 0, 0),
  ('cant-stop-the-feeling-michal-buzaglo', 'breakdown', 28, 1),
  ('cant-stop-the-feeling-michal-buzaglo', 'slow-practice', 76, 2),
  ('cant-stop-the-feeling-michal-buzaglo', 'full-speed', 137, 3),
  ('unholy-guy-ravid', 'full-performance', 0, 0),
  ('unholy-guy-ravid', 'breakdown', 19, 1),
  ('unholy-guy-ravid', 'slow-practice', 50, 2),
  ('unholy-guy-ravid', 'full-speed', 90, 3),
  ('unavailable-michal-buzaglo', 'full-performance', 0, 0),
  ('unavailable-michal-buzaglo', 'breakdown', 21, 1),
  ('unavailable-michal-buzaglo', 'slow-practice', 57, 2),
  ('unavailable-michal-buzaglo', 'full-speed', 103, 3),
  ('calm-down-guy-ravid', 'full-performance', 0, 0),
  ('calm-down-guy-ravid', 'breakdown', 26, 1),
  ('calm-down-guy-ravid', 'slow-practice', 70, 2),
  ('calm-down-guy-ravid', 'full-speed', 127, 3),
  ('rush-michal-buzaglo', 'full-performance', 0, 0),
  ('rush-michal-buzaglo', 'breakdown', 20, 1),
  ('rush-michal-buzaglo', 'slow-practice', 54, 2),
  ('rush-michal-buzaglo', 'full-speed', 99, 3),
  ('sad-girlz-luv-money-guy-ravid', 'full-performance', 0, 0),
  ('sad-girlz-luv-money-guy-ravid', 'breakdown', 19, 1),
  ('sad-girlz-luv-money-guy-ravid', 'slow-practice', 50, 2),
  ('sad-girlz-luv-money-guy-ravid', 'full-speed', 91, 3),
  ('blessed-michal-buzaglo', 'full-performance', 0, 0),
  ('blessed-michal-buzaglo', 'breakdown', 22, 1),
  ('blessed-michal-buzaglo', 'slow-practice', 59, 2),
  ('blessed-michal-buzaglo', 'full-speed', 106, 3),
  ('break-my-soul-guy-ravid', 'full-performance', 0, 0),
  ('break-my-soul-guy-ravid', 'breakdown', 33, 1),
  ('break-my-soul-guy-ravid', 'slow-practice', 89, 2),
  ('break-my-soul-guy-ravid', 'full-speed', 161, 3),
  ('formation-michal-buzaglo', 'full-performance', 0, 0),
  ('formation-michal-buzaglo', 'breakdown', 25, 1),
  ('formation-michal-buzaglo', 'slow-practice', 66, 2),
  ('formation-michal-buzaglo', 'full-speed', 119, 3),
  ('umbrella-guy-ravid', 'full-performance', 0, 0),
  ('umbrella-guy-ravid', 'breakdown', 33, 1),
  ('umbrella-guy-ravid', 'slow-practice', 88, 2),
  ('umbrella-guy-ravid', 'full-speed', 160, 3),
  ('dont-stop-the-music-michal-buzaglo', 'full-performance', 0, 0),
  ('dont-stop-the-music-michal-buzaglo', 'breakdown', 33, 1),
  ('dont-stop-the-music-michal-buzaglo', 'slow-practice', 87, 2),
  ('dont-stop-the-music-michal-buzaglo', 'full-speed', 158, 3),
  ('7-rings-guy-ravid', 'full-performance', 0, 0),
  ('7-rings-guy-ravid', 'breakdown', 21, 1),
  ('7-rings-guy-ravid', 'slow-practice', 57, 2),
  ('7-rings-guy-ravid', 'full-speed', 103, 3),
  ('break-free-michal-buzaglo', 'full-performance', 0, 0),
  ('break-free-michal-buzaglo', 'breakdown', 26, 1),
  ('break-free-michal-buzaglo', 'slow-practice', 68, 2),
  ('break-free-michal-buzaglo', 'full-speed', 124, 3);

