-- Chapter markers for Gisha Gmisha Foundations lessons, sourced from
-- Premiere chapter CSVs under video-edit/.../קורס יסודות/*/FINAL/*.csv.
-- Timecodes are HH:MM:SS:FF at 60fps, converted to whole seconds (In point).

INSERT INTO course_lesson_chapters
  (course_kind, course_slug, lesson_id, chapter_id, time_seconds, sort_order)
VALUES
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-opening', 0, 0),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-head-neck', 23, 1),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-shoulders-blades', 77, 2),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-arm-sequence', 158, 3),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-pelvis', 250, 4),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-knees', 311, 5),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-ankles', 322, 6),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-combined-exercise', 379, 7),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-balance', 465, 8),
  ('external_course', 'gisha-gmisha-foundations', 'warmup', 'gisha-warmup-dynamic-warm-up', 519, 9),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-opening', 0, 0),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-posture', 6, 1),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-tabletop-back', 56, 2),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-symmetrical-thinking', 80, 3),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-neck-in-abs-exercises', 130, 4),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-using-gravity', 175, 5),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-triangle-pose', 211, 6),
  ('external_course', 'gisha-gmisha-foundations', 'head-neck', 'gisha-head-neck-exercises-strength-stretches', 273, 7),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades', 'gisha-shoulder-blades-opening-intro', 1, 0),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades', 'gisha-shoulder-blades-stretches-release-relaxation', 98, 1),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades', 'gisha-shoulder-blades-posture-correction', 238, 2),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades', 'gisha-shoulder-blades-strength-exercises-proper-work', 392, 3),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades', 'gisha-shoulder-blades-joint-mobility', 492, 4),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-opening', 6, 0),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-step-1', 68, 1),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-step-2', 109, 2),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-step-3', 148, 3),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-seated-explanation', 200, 4),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-other-side', 237, 5),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-variation-without-the-block', 278, 6),
  ('external_course', 'gisha-gmisha-foundations', 'shoulder-blades-physio-exercise', 'gisha-shoulder-blades-physio-exercise-common-mistake', 290, 7),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-opening-posture', 0, 0),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-working-stance-pelvis', 47, 1),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-movement', 90, 2),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-arch-round', 142, 3),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-erectors-work-strength', 168, 4),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-prone-practice-strength', 246, 5),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-chair-practice-stretch', 248, 6),
  ('external_course', 'gisha-gmisha-foundations', 'spine-abs', 'gisha-spine-abs-cube-exercises', 361, 7),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-opening', 0, 0),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-more-than-physical-flexibility', 6, 1),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-gisha', 19, 2),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-personal-adaptation', 29, 3),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-gmisha', 49, 4),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-changing-habits', 53, 5),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-we-deserve-it', 74, 6),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-im-here-for-you', 92, 7),
  ('external_course', 'gisha-gmisha-foundations', 'summary', 'gisha-summary-summary', 106, 8);

INSERT INTO chapter_i18n (chapter_id, locale, label) VALUES
  ('gisha-warmup-opening', 'he', 'פתיחה'),
  ('gisha-warmup-opening', 'en', 'Opening'),
  ('gisha-warmup-head-neck', 'he', 'ראש וצוואר'),
  ('gisha-warmup-head-neck', 'en', 'Head & neck'),
  ('gisha-warmup-shoulders-blades', 'he', 'כתפיים ושכמות'),
  ('gisha-warmup-shoulders-blades', 'en', 'Shoulders & blades'),
  ('gisha-warmup-arm-sequence', 'he', 'רצף ידיים'),
  ('gisha-warmup-arm-sequence', 'en', 'Arm sequence'),
  ('gisha-warmup-pelvis', 'he', 'אגן'),
  ('gisha-warmup-pelvis', 'en', 'Pelvis'),
  ('gisha-warmup-knees', 'he', 'ברכיים'),
  ('gisha-warmup-knees', 'en', 'Knees'),
  ('gisha-warmup-ankles', 'he', 'קרסוליים'),
  ('gisha-warmup-ankles', 'en', 'Ankles'),
  ('gisha-warmup-combined-exercise', 'he', 'תרגיל משולב'),
  ('gisha-warmup-combined-exercise', 'en', 'Combined exercise'),
  ('gisha-warmup-balance', 'he', 'שיווי משקל'),
  ('gisha-warmup-balance', 'en', 'Balance'),
  ('gisha-warmup-dynamic-warm-up', 'he', 'חימום דינאמי'),
  ('gisha-warmup-dynamic-warm-up', 'en', 'Dynamic warm-up'),
  ('gisha-head-neck-opening', 'he', 'פתיחה'),
  ('gisha-head-neck-opening', 'en', 'Opening'),
  ('gisha-head-neck-posture', 'he', 'יציבה'),
  ('gisha-head-neck-posture', 'en', 'Posture'),
  ('gisha-head-neck-tabletop-back', 'he', 'גב שולחן'),
  ('gisha-head-neck-tabletop-back', 'en', 'Tabletop back'),
  ('gisha-head-neck-symmetrical-thinking', 'he', 'חשיבה סימטרית'),
  ('gisha-head-neck-symmetrical-thinking', 'en', 'Symmetrical thinking'),
  ('gisha-head-neck-neck-in-abs-exercises', 'he', 'הצוואר בתרגילי בטן'),
  ('gisha-head-neck-neck-in-abs-exercises', 'en', 'Neck in abs exercises'),
  ('gisha-head-neck-using-gravity', 'he', 'להיעזר בכוח המשיכה'),
  ('gisha-head-neck-using-gravity', 'en', 'Using gravity'),
  ('gisha-head-neck-triangle-pose', 'he', 'תנוחת המשולש'),
  ('gisha-head-neck-triangle-pose', 'en', 'Triangle pose'),
  ('gisha-head-neck-exercises-strength-stretches', 'he', 'תרגילים - חיזוק ומתיחות'),
  ('gisha-head-neck-exercises-strength-stretches', 'en', 'Exercises — strength & stretches'),
  ('gisha-shoulder-blades-opening-intro', 'he', 'פתיחה והקדמה'),
  ('gisha-shoulder-blades-opening-intro', 'en', 'Opening & intro'),
  ('gisha-shoulder-blades-stretches-release-relaxation', 'he', 'מתיחות / שחרור והרפייה'),
  ('gisha-shoulder-blades-stretches-release-relaxation', 'en', 'Stretches / release & relaxation'),
  ('gisha-shoulder-blades-posture-correction', 'he', 'תיקון יציבה'),
  ('gisha-shoulder-blades-posture-correction', 'en', 'Posture correction'),
  ('gisha-shoulder-blades-strength-exercises-proper-work', 'he', 'תרגילי חיזוק / עבודה נכונה'),
  ('gisha-shoulder-blades-strength-exercises-proper-work', 'en', 'Strength exercises / proper work'),
  ('gisha-shoulder-blades-joint-mobility', 'he', 'תנועתיות במפרק'),
  ('gisha-shoulder-blades-joint-mobility', 'en', 'Joint mobility'),
  ('gisha-shoulder-blades-physio-exercise-opening', 'he', 'פתיחה'),
  ('gisha-shoulder-blades-physio-exercise-opening', 'en', 'Opening'),
  ('gisha-shoulder-blades-physio-exercise-step-1', 'he', 'שלב 1'),
  ('gisha-shoulder-blades-physio-exercise-step-1', 'en', 'Step 1'),
  ('gisha-shoulder-blades-physio-exercise-step-2', 'he', 'שלב 2'),
  ('gisha-shoulder-blades-physio-exercise-step-2', 'en', 'Step 2'),
  ('gisha-shoulder-blades-physio-exercise-step-3', 'he', 'שלב 3'),
  ('gisha-shoulder-blades-physio-exercise-step-3', 'en', 'Step 3'),
  ('gisha-shoulder-blades-physio-exercise-seated-explanation', 'he', 'הסבר בישיבה'),
  ('gisha-shoulder-blades-physio-exercise-seated-explanation', 'en', 'Seated explanation'),
  ('gisha-shoulder-blades-physio-exercise-other-side', 'he', 'צד שני'),
  ('gisha-shoulder-blades-physio-exercise-other-side', 'en', 'Other side'),
  ('gisha-shoulder-blades-physio-exercise-variation-without-the-block', 'he', 'וריאציה בלי הבלוק'),
  ('gisha-shoulder-blades-physio-exercise-variation-without-the-block', 'en', 'Variation without the block'),
  ('gisha-shoulder-blades-physio-exercise-common-mistake', 'he', 'טעות נפוצה'),
  ('gisha-shoulder-blades-physio-exercise-common-mistake', 'en', 'Common mistake'),
  ('gisha-spine-abs-opening-posture', 'he', 'פתיחה - יציבה'),
  ('gisha-spine-abs-opening-posture', 'en', 'Opening — posture'),
  ('gisha-spine-abs-working-stance-pelvis', 'he', 'מנח עבודה - אגן'),
  ('gisha-spine-abs-working-stance-pelvis', 'en', 'Working stance — pelvis'),
  ('gisha-spine-abs-movement', 'he', 'תנועה'),
  ('gisha-spine-abs-movement', 'en', 'Movement'),
  ('gisha-spine-abs-arch-round', 'he', 'קימור קיעור'),
  ('gisha-spine-abs-arch-round', 'en', 'Arch & round'),
  ('gisha-spine-abs-erectors-work-strength', 'he', 'עבודה על הזוקפים (חיזוק)'),
  ('gisha-spine-abs-erectors-work-strength', 'en', 'Erectors work (strength)'),
  ('gisha-spine-abs-prone-practice-strength', 'he', 'תרגול על הבטן (חיזוק)'),
  ('gisha-spine-abs-prone-practice-strength', 'en', 'Prone practice (strength)'),
  ('gisha-spine-abs-chair-practice-stretch', 'he', 'תרגול עם כיסא (מתיחה)'),
  ('gisha-spine-abs-chair-practice-stretch', 'en', 'Chair practice (stretch)'),
  ('gisha-spine-abs-cube-exercises', 'he', 'תרגילים עם קובייה'),
  ('gisha-spine-abs-cube-exercises', 'en', 'Cube exercises'),
  ('gisha-summary-opening', 'he', 'פתיחה'),
  ('gisha-summary-opening', 'en', 'Opening'),
  ('gisha-summary-more-than-physical-flexibility', 'he', 'יותר מרק גמישות פיזית'),
  ('gisha-summary-more-than-physical-flexibility', 'en', 'More than physical flexibility'),
  ('gisha-summary-gisha', 'he', 'גיש"ה'),
  ('gisha-summary-gisha', 'en', '“Gisha”'),
  ('gisha-summary-personal-adaptation', 'he', 'התאמה אישית'),
  ('gisha-summary-personal-adaptation', 'en', 'Personal adaptation'),
  ('gisha-summary-gmisha', 'he', 'גמיש"ה'),
  ('gisha-summary-gmisha', 'en', '“Gmisha”'),
  ('gisha-summary-changing-habits', 'he', 'שינוי הרגלים'),
  ('gisha-summary-changing-habits', 'en', 'Changing habits'),
  ('gisha-summary-we-deserve-it', 'he', 'מגיע לנו'),
  ('gisha-summary-we-deserve-it', 'en', 'We deserve it'),
  ('gisha-summary-im-here-for-you', 'he', 'אני כאן בשבילכם'),
  ('gisha-summary-im-here-for-you', 'en', 'I''m here for you'),
  ('gisha-summary-summary', 'he', 'סיכום'),
  ('gisha-summary-summary', 'en', 'Summary');
