/**
 * Catalog types + **temporary in-memory mock routines**.
 * Replace data access with server/CMS fetches when the API is ready;
 * keep these shapes stable so UI can swap the source without rewrites.
 */
import type { Locale } from "@/lib/i18n/config";
import { localePath } from "@/lib/i18n/path";

export type DanceStyleKey =
  | "jazz-funk"
  | "hip-hop"
  | "heels"
  | "jazz"
  | "afro"
  | "dancehall"
  | "voguing";
export type LevelKey = "intermediate" | "advanced" | "all-levels";
export type TagKey =
  | DanceStyleKey
  | "performance"
  | "groove"
  | "musicality"
  | "body-control";
export type ChapterId =
  | "full-performance"
  | "breakdown"
  | "slow-practice"
  | "full-speed";

export interface VideoChapter {
  id: ChapterId;
  /** Timestamp in seconds where this section of the routine begins. */
  time: number;
}

export interface RoutineRecord {
  slug: string;
  title: string;
  instructorSlug: string;
  level: LevelKey;
  style: DanceStyleKey;
  /** Filter tags (style + technique labels). MOCK demo metadata. */
  tags: TagKey[];
  songName: string;
  artist: string;
  bpm: string;
  /** Duration timestamp without locale suffix, e.g. "3:23". */
  length: string;
  poster: string;
  videoSrc: string;
  chapters: VideoChapter[];
  checkoutHref: string;
  pricing: {
    original: number;
    earlyBird: number;
  };
}

const SAMPLE_VIDEO_SRC =
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";

/** @textScraped scripts/verify-mock-db-parity.ts locates this array by its literal `export const ROUTINES...` source text, not a TS import — keep it exported. */
export const ROUTINES: RoutineRecord[] = [
  // MOCK combinations for demo UI — songs/artists are placeholders (licensing TBD).
  {
    slug: "levitating",
    title: "Levitating",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "performance"],
    songName: "Levitating",
    artist: "Dua Lipa",
    bpm: "103 BPM",
    length: "3:23",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 58 },
      { id: "full-speed", time: 96 },
    ],
    checkoutHref: "/checkout/levitating",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "kill-bill",
    title: "Kill Bill",
    instructorSlug: "daniel-cohen",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "groove", "musicality"],
    songName: "Kill Bill",
    artist: "SZA",
    bpm: "89 BPM",
    length: "2:33",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 20 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 92 },
    ],
    checkoutHref: "/checkout/kill-bill",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "earned-it",
    title: "Earned It",
    instructorSlug: "noa-sagi",
    level: "all-levels",
    style: "heels",
    tags: ["heels", "body-control", "performance"],
    songName: "Earned It",
    artist: "The Weeknd",
    bpm: "120 BPM",
    length: "4:10",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 60 },
      { id: "full-speed", time: 98 },
    ],
    checkoutHref: "/checkout/earned-it",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "levitating-maya-azulai",
    title: "Levitating",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "performance"],
    songName: "Levitating",
    artist: "Dua Lipa",
    bpm: "103 BPM",
    length: "3:23",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 65 },
      { id: "full-speed", time: 118 },
    ],
    checkoutHref: "/checkout/levitating-maya-azulai",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "dont-start-now-tali-mizrahi",
    title: "Don't Start Now",
    instructorSlug: "tali-mizrahi",
    level: "advanced",
    style: "jazz-funk",
    tags: ["jazz-funk", "groove"],
    songName: "Don't Start Now",
    artist: "Dua Lipa",
    bpm: "124 BPM",
    length: "3:03",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 59 },
      { id: "full-speed", time: 106 },
    ],
    checkoutHref: "/checkout/dont-start-now-tali-mizrahi",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "physical-yael-bar",
    title: "Physical",
    instructorSlug: "yael-bar",
    level: "all-levels",
    style: "jazz-funk",
    tags: ["jazz-funk", "musicality"],
    songName: "Physical",
    artist: "Dua Lipa",
    bpm: "147 BPM",
    length: "3:13",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 62 },
      { id: "full-speed", time: 112 },
    ],
    checkoutHref: "/checkout/physical-yael-bar",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "about-damn-time-maya-azulai",
    title: "About Damn Time",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "body-control"],
    songName: "About Damn Time",
    artist: "Lizzo",
    bpm: "109 BPM",
    length: "3:11",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 61 },
      { id: "full-speed", time: 111 },
    ],
    checkoutHref: "/checkout/about-damn-time-maya-azulai",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "good-as-hell-tali-mizrahi",
    title: "Good as Hell",
    instructorSlug: "tali-mizrahi",
    level: "advanced",
    style: "jazz-funk",
    tags: ["jazz-funk", "performance"],
    songName: "Good as Hell",
    artist: "Lizzo",
    bpm: "96 BPM",
    length: "2:39",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 51 },
      { id: "full-speed", time: 92 },
    ],
    checkoutHref: "/checkout/good-as-hell-tali-mizrahi",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "flowers-yael-bar",
    title: "Flowers",
    instructorSlug: "yael-bar",
    level: "all-levels",
    style: "jazz-funk",
    tags: ["jazz-funk", "groove"],
    songName: "Flowers",
    artist: "Miley Cyrus",
    bpm: "118 BPM",
    length: "3:20",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/flowers-yael-bar",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "shirt-maya-azulai",
    title: "Shirt",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "musicality"],
    songName: "Shirt",
    artist: "SZA",
    bpm: "120 BPM",
    length: "3:01",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 58 },
      { id: "full-speed", time: 105 },
    ],
    checkoutHref: "/checkout/shirt-maya-azulai",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "blinding-lights-tali-mizrahi",
    title: "Blinding Lights",
    instructorSlug: "tali-mizrahi",
    level: "advanced",
    style: "jazz-funk",
    tags: ["jazz-funk", "body-control"],
    songName: "Blinding Lights",
    artist: "The Weeknd",
    bpm: "171 BPM",
    length: "3:20",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/blinding-lights-tali-mizrahi",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "need-to-know-yael-bar",
    title: "Need to Know",
    instructorSlug: "yael-bar",
    level: "all-levels",
    style: "jazz-funk",
    tags: ["jazz-funk", "performance"],
    songName: "Need to Know",
    artist: "Doja Cat",
    bpm: "130 BPM",
    length: "3:30",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 122 },
    ],
    checkoutHref: "/checkout/need-to-know-yael-bar",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "kiss-me-more-maya-azulai",
    title: "Kiss Me More",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "groove"],
    songName: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    bpm: "111 BPM",
    length: "3:28",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 121 },
    ],
    checkoutHref: "/checkout/kiss-me-more-maya-azulai",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "woman-tali-mizrahi",
    title: "Woman",
    instructorSlug: "tali-mizrahi",
    level: "advanced",
    style: "jazz-funk",
    tags: ["jazz-funk", "musicality"],
    songName: "Woman",
    artist: "Doja Cat",
    bpm: "128 BPM",
    length: "2:52",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 100 },
    ],
    checkoutHref: "/checkout/woman-tali-mizrahi",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "nice-for-what-yael-bar",
    title: "Nice For What",
    instructorSlug: "yael-bar",
    level: "all-levels",
    style: "jazz-funk",
    tags: ["jazz-funk", "body-control"],
    songName: "Nice For What",
    artist: "Drake",
    bpm: "93 BPM",
    length: "3:30",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 122 },
    ],
    checkoutHref: "/checkout/nice-for-what-yael-bar",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "as-it-was-maya-azulai",
    title: "As It Was",
    instructorSlug: "maya-azulai",
    level: "intermediate",
    style: "jazz-funk",
    tags: ["jazz-funk", "performance"],
    songName: "As It Was",
    artist: "Harry Styles",
    bpm: "174 BPM",
    length: "2:47",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 20 },
      { id: "slow-practice", time: 53 },
      { id: "full-speed", time: 97 },
    ],
    checkoutHref: "/checkout/as-it-was-maya-azulai",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "anti-hero-tali-mizrahi",
    title: "Anti-Hero",
    instructorSlug: "tali-mizrahi",
    level: "advanced",
    style: "jazz-funk",
    tags: ["jazz-funk", "groove"],
    songName: "Anti-Hero",
    artist: "Taylor Swift",
    bpm: "97 BPM",
    length: "3:20",
    poster: "/routine-poster-midnight-static.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/anti-hero-tali-mizrahi",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "about-damn-time-daniel-cohen",
    title: "About Damn Time",
    instructorSlug: "daniel-cohen",
    level: "intermediate",
    style: "hip-hop",
    tags: ["hip-hop", "performance"],
    songName: "About Damn Time",
    artist: "Lizzo",
    bpm: "109 BPM",
    length: "3:11",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 61 },
      { id: "full-speed", time: 111 },
    ],
    checkoutHref: "/checkout/about-damn-time-daniel-cohen",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "kill-bill-oran-ben-david",
    title: "Kill Bill",
    instructorSlug: "oran-ben-david",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "groove"],
    songName: "Kill Bill",
    artist: "SZA",
    bpm: "89 BPM",
    length: "2:33",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 18 },
      { id: "slow-practice", time: 49 },
      { id: "full-speed", time: 89 },
    ],
    checkoutHref: "/checkout/kill-bill-oran-ben-david",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "creepin-amit-sharabi",
    title: "Creepin'",
    instructorSlug: "amit-sharabi",
    level: "all-levels",
    style: "hip-hop",
    tags: ["hip-hop", "musicality"],
    songName: "Creepin'",
    artist: "Metro Boomin, The Weeknd, 21 Savage",
    bpm: "98 BPM",
    length: "3:41",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 71 },
      { id: "full-speed", time: 128 },
    ],
    checkoutHref: "/checkout/creepin-amit-sharabi",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "first-class-daniel-cohen",
    title: "First Class",
    instructorSlug: "daniel-cohen",
    level: "intermediate",
    style: "hip-hop",
    tags: ["hip-hop", "body-control"],
    songName: "First Class",
    artist: "Jack Harlow",
    bpm: "107 BPM",
    length: "2:53",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 100 },
    ],
    checkoutHref: "/checkout/first-class-daniel-cohen",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "industry-baby-oran-ben-david",
    title: "Industry Baby",
    instructorSlug: "oran-ben-david",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "performance"],
    songName: "Industry Baby",
    artist: "Lil Nas X & Jack Harlow",
    bpm: "150 BPM",
    length: "3:32",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 68 },
      { id: "full-speed", time: 123 },
    ],
    checkoutHref: "/checkout/industry-baby-oran-ben-david",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "god-s-plan-amit-sharabi",
    title: "God's Plan",
    instructorSlug: "amit-sharabi",
    level: "all-levels",
    style: "hip-hop",
    tags: ["hip-hop", "groove"],
    songName: "God's Plan",
    artist: "Drake",
    bpm: "77 BPM",
    length: "3:18",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 63 },
      { id: "full-speed", time: 115 },
    ],
    checkoutHref: "/checkout/god-s-plan-amit-sharabi",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "nice-for-what-daniel-cohen",
    title: "Nice For What",
    instructorSlug: "daniel-cohen",
    level: "intermediate",
    style: "hip-hop",
    tags: ["hip-hop", "musicality"],
    songName: "Nice For What",
    artist: "Drake",
    bpm: "93 BPM",
    length: "3:30",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 122 },
    ],
    checkoutHref: "/checkout/nice-for-what-daniel-cohen",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "savage-oran-ben-david",
    title: "Savage",
    instructorSlug: "oran-ben-david",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "body-control"],
    songName: "Savage",
    artist: "Megan Thee Stallion",
    bpm: "127 BPM",
    length: "2:35",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 50 },
      { id: "full-speed", time: 90 },
    ],
    checkoutHref: "/checkout/savage-oran-ben-david",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "body-amit-sharabi",
    title: "Body",
    instructorSlug: "amit-sharabi",
    level: "all-levels",
    style: "hip-hop",
    tags: ["hip-hop", "performance"],
    songName: "Body",
    artist: "Megan Thee Stallion",
    bpm: "123 BPM",
    length: "2:51",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 99 },
    ],
    checkoutHref: "/checkout/body-amit-sharabi",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "get-ur-freak-on-daniel-cohen",
    title: "Get Ur Freak On",
    instructorSlug: "daniel-cohen",
    level: "intermediate",
    style: "hip-hop",
    tags: ["hip-hop", "groove"],
    songName: "Get Ur Freak On",
    artist: "Missy Elliott",
    bpm: "100 BPM",
    length: "3:53",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 28 },
      { id: "slow-practice", time: 75 },
      { id: "full-speed", time: 135 },
    ],
    checkoutHref: "/checkout/get-ur-freak-on-daniel-cohen",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "work-it-oran-ben-david",
    title: "Work It",
    instructorSlug: "oran-ben-david",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "musicality"],
    songName: "Work It",
    artist: "Missy Elliott",
    bpm: "100 BPM",
    length: "3:23",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 65 },
      { id: "full-speed", time: 118 },
    ],
    checkoutHref: "/checkout/work-it-oran-ben-david",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "sicko-mode-amit-sharabi",
    title: "Sicko Mode",
    instructorSlug: "amit-sharabi",
    level: "all-levels",
    style: "hip-hop",
    tags: ["hip-hop", "body-control"],
    songName: "Sicko Mode",
    artist: "Travis Scott",
    bpm: "155 BPM",
    length: "5:12",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 37 },
      { id: "slow-practice", time: 100 },
      { id: "full-speed", time: 181 },
    ],
    checkoutHref: "/checkout/sicko-mode-amit-sharabi",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "humble-daniel-cohen",
    title: "Humble",
    instructorSlug: "daniel-cohen",
    level: "intermediate",
    style: "hip-hop",
    tags: ["hip-hop", "performance"],
    songName: "Humble",
    artist: "Kendrick Lamar",
    bpm: "150 BPM",
    length: "2:57",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 57 },
      { id: "full-speed", time: 103 },
    ],
    checkoutHref: "/checkout/humble-daniel-cohen",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "dna-oran-ben-david",
    title: "DNA",
    instructorSlug: "oran-ben-david",
    level: "advanced",
    style: "hip-hop",
    tags: ["hip-hop", "groove"],
    songName: "DNA",
    artist: "Kendrick Lamar",
    bpm: "140 BPM",
    length: "3:05",
    poster: "/routine-poster-neon-nights.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 59 },
      { id: "full-speed", time: 107 },
    ],
    checkoutHref: "/checkout/dna-oran-ben-david",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "kill-bill-noa-sagi",
    title: "Kill Bill",
    instructorSlug: "noa-sagi",
    level: "intermediate",
    style: "heels",
    tags: ["heels", "performance"],
    songName: "Kill Bill",
    artist: "SZA",
    bpm: "89 BPM",
    length: "2:33",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 18 },
      { id: "slow-practice", time: 49 },
      { id: "full-speed", time: 89 },
    ],
    checkoutHref: "/checkout/kill-bill-noa-sagi",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "snooze-maya-rozin",
    title: "Snooze",
    instructorSlug: "maya-rozin",
    level: "advanced",
    style: "heels",
    tags: ["heels", "groove"],
    songName: "Snooze",
    artist: "SZA",
    bpm: "77 BPM",
    length: "3:21",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 117 },
    ],
    checkoutHref: "/checkout/snooze-maya-rozin",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "shirt-noga-eliyahu",
    title: "Shirt",
    instructorSlug: "noga-eliyahu",
    level: "all-levels",
    style: "heels",
    tags: ["heels", "musicality"],
    songName: "Shirt",
    artist: "SZA",
    bpm: "120 BPM",
    length: "3:01",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 58 },
      { id: "full-speed", time: 105 },
    ],
    checkoutHref: "/checkout/shirt-noga-eliyahu",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "earned-it-noa-sagi",
    title: "Earned It",
    instructorSlug: "noa-sagi",
    level: "intermediate",
    style: "heels",
    tags: ["heels", "body-control"],
    songName: "Earned It",
    artist: "The Weeknd",
    bpm: "120 BPM",
    length: "4:10",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 30 },
      { id: "slow-practice", time: 80 },
      { id: "full-speed", time: 145 },
    ],
    checkoutHref: "/checkout/earned-it-noa-sagi",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "die-for-you-maya-rozin",
    title: "Die For You",
    instructorSlug: "maya-rozin",
    level: "advanced",
    style: "heels",
    tags: ["heels", "performance"],
    songName: "Die For You",
    artist: "The Weeknd",
    bpm: "67 BPM",
    length: "4:20",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 31 },
      { id: "slow-practice", time: 83 },
      { id: "full-speed", time: 151 },
    ],
    checkoutHref: "/checkout/die-for-you-maya-rozin",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "creepin-noga-eliyahu",
    title: "Creepin'",
    instructorSlug: "noga-eliyahu",
    level: "all-levels",
    style: "heels",
    tags: ["heels", "groove"],
    songName: "Creepin'",
    artist: "Metro Boomin, The Weeknd, 21 Savage",
    bpm: "98 BPM",
    length: "3:41",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 71 },
      { id: "full-speed", time: 128 },
    ],
    checkoutHref: "/checkout/creepin-noga-eliyahu",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "need-to-know-noa-sagi",
    title: "Need to Know",
    instructorSlug: "noa-sagi",
    level: "intermediate",
    style: "heels",
    tags: ["heels", "musicality"],
    songName: "Need to Know",
    artist: "Doja Cat",
    bpm: "130 BPM",
    length: "3:30",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 122 },
    ],
    checkoutHref: "/checkout/need-to-know-noa-sagi",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "kiss-me-more-maya-rozin",
    title: "Kiss Me More",
    instructorSlug: "maya-rozin",
    level: "advanced",
    style: "heels",
    tags: ["heels", "body-control"],
    songName: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    bpm: "111 BPM",
    length: "3:28",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 121 },
    ],
    checkoutHref: "/checkout/kiss-me-more-maya-rozin",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "body-party-noga-eliyahu",
    title: "Body Party",
    instructorSlug: "noga-eliyahu",
    level: "all-levels",
    style: "heels",
    tags: ["heels", "performance"],
    songName: "Body Party",
    artist: "Ciara",
    bpm: "67 BPM",
    length: "4:00",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 29 },
      { id: "slow-practice", time: 77 },
      { id: "full-speed", time: 139 },
    ],
    checkoutHref: "/checkout/body-party-noga-eliyahu",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "ride-noa-sagi",
    title: "Ride",
    instructorSlug: "noa-sagi",
    level: "intermediate",
    style: "heels",
    tags: ["heels", "groove"],
    songName: "Ride",
    artist: "Ciara",
    bpm: "65 BPM",
    length: "4:36",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 33 },
      { id: "slow-practice", time: 88 },
      { id: "full-speed", time: 160 },
    ],
    checkoutHref: "/checkout/ride-noa-sagi",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "2-on-maya-rozin",
    title: "2 On",
    instructorSlug: "maya-rozin",
    level: "advanced",
    style: "heels",
    tags: ["heels", "musicality"],
    songName: "2 On",
    artist: "Tinashe",
    bpm: "100 BPM",
    length: "3:33",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 68 },
      { id: "full-speed", time: 124 },
    ],
    checkoutHref: "/checkout/2-on-maya-rozin",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "distraction-noga-eliyahu",
    title: "Distraction",
    instructorSlug: "noga-eliyahu",
    level: "all-levels",
    style: "heels",
    tags: ["heels", "body-control"],
    songName: "Distraction",
    artist: "Kehlani",
    bpm: "100 BPM",
    length: "3:17",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 63 },
      { id: "full-speed", time: 114 },
    ],
    checkoutHref: "/checkout/distraction-noga-eliyahu",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "me-and-u-noa-sagi",
    title: "Me & U",
    instructorSlug: "noa-sagi",
    level: "intermediate",
    style: "heels",
    tags: ["heels", "performance"],
    songName: "Me & U",
    artist: "Cassie",
    bpm: "130 BPM",
    length: "3:34",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 68 },
      { id: "full-speed", time: 124 },
    ],
    checkoutHref: "/checkout/me-and-u-noa-sagi",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "rock-the-boat-maya-rozin",
    title: "Rock the Boat",
    instructorSlug: "maya-rozin",
    level: "advanced",
    style: "heels",
    tags: ["heels", "groove"],
    songName: "Rock the Boat",
    artist: "Aaliyah",
    bpm: "75 BPM",
    length: "4:04",
    poster: "/routine-poster-velvet-heels.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 29 },
      { id: "slow-practice", time: 78 },
      { id: "full-speed", time: 142 },
    ],
    checkoutHref: "/checkout/rock-the-boat-maya-rozin",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "easy-on-me-yasmin-kadosh",
    title: "Easy On Me",
    instructorSlug: "yasmin-kadosh",
    level: "intermediate",
    style: "jazz",
    tags: ["jazz", "performance"],
    songName: "Easy On Me",
    artist: "Adele",
    bpm: "62 BPM",
    length: "3:44",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 72 },
      { id: "full-speed", time: 130 },
    ],
    checkoutHref: "/checkout/easy-on-me-yasmin-kadosh",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "rolling-in-the-deep-omer-tzur",
    title: "Rolling in the Deep",
    instructorSlug: "omer-tzur",
    level: "advanced",
    style: "jazz",
    tags: ["jazz", "groove"],
    songName: "Rolling in the Deep",
    artist: "Adele",
    bpm: "105 BPM",
    length: "3:48",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 73 },
      { id: "full-speed", time: 132 },
    ],
    checkoutHref: "/checkout/rolling-in-the-deep-omer-tzur",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "stay-with-me-hila-ben-ari",
    title: "Stay With Me",
    instructorSlug: "hila-ben-ari",
    level: "all-levels",
    style: "jazz",
    tags: ["jazz", "musicality"],
    songName: "Stay With Me",
    artist: "Sam Smith",
    bpm: "79 BPM",
    length: "2:53",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 100 },
    ],
    checkoutHref: "/checkout/stay-with-me-hila-ben-ari",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "unholy-yasmin-kadosh",
    title: "Unholy",
    instructorSlug: "yasmin-kadosh",
    level: "intermediate",
    style: "jazz",
    tags: ["jazz", "body-control"],
    songName: "Unholy",
    artist: "Sam Smith ft. Kim Petras",
    bpm: "131 BPM",
    length: "2:36",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 50 },
      { id: "full-speed", time: 90 },
    ],
    checkoutHref: "/checkout/unholy-yasmin-kadosh",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "ocean-eyes-omer-tzur",
    title: "Ocean Eyes",
    instructorSlug: "omer-tzur",
    level: "advanced",
    style: "jazz",
    tags: ["jazz", "performance"],
    songName: "Ocean Eyes",
    artist: "Billie Eilish",
    bpm: "79 BPM",
    length: "3:20",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/ocean-eyes-omer-tzur",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "happier-than-ever-hila-ben-ari",
    title: "Happier Than Ever",
    instructorSlug: "hila-ben-ari",
    level: "all-levels",
    style: "jazz",
    tags: ["jazz", "groove"],
    songName: "Happier Than Ever",
    artist: "Billie Eilish",
    bpm: "87 BPM",
    length: "4:58",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 36 },
      { id: "slow-practice", time: 95 },
      { id: "full-speed", time: 173 },
    ],
    checkoutHref: "/checkout/happier-than-ever-hila-ben-ari",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "best-part-yasmin-kadosh",
    title: "Best Part",
    instructorSlug: "yasmin-kadosh",
    level: "intermediate",
    style: "jazz",
    tags: ["jazz", "musicality"],
    songName: "Best Part",
    artist: "H.E.R. ft. Daniel Caesar",
    bpm: "68 BPM",
    length: "3:29",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 121 },
    ],
    checkoutHref: "/checkout/best-part-yasmin-kadosh",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "someone-you-loved-omer-tzur",
    title: "Someone You Loved",
    instructorSlug: "omer-tzur",
    level: "advanced",
    style: "jazz",
    tags: ["jazz", "body-control"],
    songName: "Someone You Loved",
    artist: "Lewis Capaldi",
    bpm: "110 BPM",
    length: "3:02",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 58 },
      { id: "full-speed", time: 106 },
    ],
    checkoutHref: "/checkout/someone-you-loved-omer-tzur",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "my-hair-hila-ben-ari",
    title: "my hair",
    instructorSlug: "hila-ben-ari",
    level: "all-levels",
    style: "jazz",
    tags: ["jazz", "performance"],
    songName: "my hair",
    artist: "Ariana Grande",
    bpm: "55 BPM",
    length: "2:41",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 52 },
      { id: "full-speed", time: 93 },
    ],
    checkoutHref: "/checkout/my-hair-hila-ben-ari",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "be-honest-yasmin-kadosh",
    title: "Be Honest",
    instructorSlug: "yasmin-kadosh",
    level: "intermediate",
    style: "jazz",
    tags: ["jazz", "groove"],
    songName: "Be Honest",
    artist: "Jorja Smith",
    bpm: "100 BPM",
    length: "3:29",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 121 },
    ],
    checkoutHref: "/checkout/be-honest-yasmin-kadosh",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "if-i-aint-got-you-omer-tzur",
    title: "If I Ain't Got You",
    instructorSlug: "omer-tzur",
    level: "advanced",
    style: "jazz",
    tags: ["jazz", "musicality"],
    songName: "If I Ain't Got You",
    artist: "Alicia Keys",
    bpm: "94 BPM",
    length: "3:48",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 73 },
      { id: "full-speed", time: 132 },
    ],
    checkoutHref: "/checkout/if-i-aint-got-you-omer-tzur",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "all-of-me-hila-ben-ari",
    title: "All of Me",
    instructorSlug: "hila-ben-ari",
    level: "all-levels",
    style: "jazz",
    tags: ["jazz", "body-control"],
    songName: "All of Me",
    artist: "John Legend",
    bpm: "63 BPM",
    length: "4:29",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 32 },
      { id: "slow-practice", time: 86 },
      { id: "full-speed", time: 156 },
    ],
    checkoutHref: "/checkout/all-of-me-hila-ben-ari",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "get-you-yasmin-kadosh",
    title: "Get You",
    instructorSlug: "yasmin-kadosh",
    level: "intermediate",
    style: "jazz",
    tags: ["jazz", "performance"],
    songName: "Get You",
    artist: "Daniel Caesar ft. Kali Uchis",
    bpm: "85 BPM",
    length: "4:08",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 30 },
      { id: "slow-practice", time: 79 },
      { id: "full-speed", time: 144 },
    ],
    checkoutHref: "/checkout/get-you-yasmin-kadosh",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "toronto-omer-tzur",
    title: "Toronto",
    instructorSlug: "omer-tzur",
    level: "advanced",
    style: "jazz",
    tags: ["jazz", "groove"],
    songName: "Toronto",
    artist: "Snoh Aalegra",
    bpm: "88 BPM",
    length: "3:07",
    poster: "/routine-poster-jazz-glow.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 60 },
      { id: "full-speed", time: 108 },
    ],
    checkoutHref: "/checkout/toronto-omer-tzur",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "be-honest-efrat-wolde",
    title: "Be Honest",
    instructorSlug: "efrat-wolde",
    level: "intermediate",
    style: "afro",
    tags: ["afro", "performance"],
    songName: "Be Honest",
    artist: "Jorja Smith",
    bpm: "100 BPM",
    length: "3:29",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 67 },
      { id: "full-speed", time: 121 },
    ],
    checkoutHref: "/checkout/be-honest-efrat-wolde",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "higher-yonatan-tesfaye",
    title: "Higher",
    instructorSlug: "yonatan-tesfaye",
    level: "advanced",
    style: "afro",
    tags: ["afro", "groove"],
    songName: "Higher",
    artist: "Tems",
    bpm: "100 BPM",
    length: "3:14",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 62 },
      { id: "full-speed", time: 113 },
    ],
    checkoutHref: "/checkout/higher-yonatan-tesfaye",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "last-last-efrat-wolde",
    title: "Last Last",
    instructorSlug: "efrat-wolde",
    level: "all-levels",
    style: "afro",
    tags: ["afro", "musicality"],
    songName: "Last Last",
    artist: "Burna Boy",
    bpm: "103 BPM",
    length: "3:15",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 62 },
      { id: "full-speed", time: 113 },
    ],
    checkoutHref: "/checkout/last-last-efrat-wolde",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "kilometre-yonatan-tesfaye",
    title: "Kilometre",
    instructorSlug: "yonatan-tesfaye",
    level: "intermediate",
    style: "afro",
    tags: ["afro", "body-control"],
    songName: "Kilometre",
    artist: "Burna Boy",
    bpm: "105 BPM",
    length: "3:33",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 68 },
      { id: "full-speed", time: 124 },
    ],
    checkoutHref: "/checkout/kilometre-yonatan-tesfaye",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "essence-efrat-wolde",
    title: "Essence",
    instructorSlug: "efrat-wolde",
    level: "advanced",
    style: "afro",
    tags: ["afro", "performance"],
    songName: "Essence",
    artist: "Wizkid ft. Tems",
    bpm: "103 BPM",
    length: "4:08",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 30 },
      { id: "slow-practice", time: 79 },
      { id: "full-speed", time: 144 },
    ],
    checkoutHref: "/checkout/essence-efrat-wolde",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "ojuelegba-yonatan-tesfaye",
    title: "Ojuelegba",
    instructorSlug: "yonatan-tesfaye",
    level: "all-levels",
    style: "afro",
    tags: ["afro", "groove"],
    songName: "Ojuelegba",
    artist: "Wizkid",
    bpm: "100 BPM",
    length: "3:47",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 73 },
      { id: "full-speed", time: 132 },
    ],
    checkoutHref: "/checkout/ojuelegba-yonatan-tesfaye",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "fall-efrat-wolde",
    title: "Fall",
    instructorSlug: "efrat-wolde",
    level: "intermediate",
    style: "afro",
    tags: ["afro", "musicality"],
    songName: "Fall",
    artist: "Davido",
    bpm: "102 BPM",
    length: "4:07",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 30 },
      { id: "slow-practice", time: 79 },
      { id: "full-speed", time: 143 },
    ],
    checkoutHref: "/checkout/fall-efrat-wolde",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "unavailable-yonatan-tesfaye",
    title: "Unavailable",
    instructorSlug: "yonatan-tesfaye",
    level: "advanced",
    style: "afro",
    tags: ["afro", "body-control"],
    songName: "Unavailable",
    artist: "Davido ft. Musa Keys",
    bpm: "107 BPM",
    length: "2:58",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 57 },
      { id: "full-speed", time: 103 },
    ],
    checkoutHref: "/checkout/unavailable-yonatan-tesfaye",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "calm-down-efrat-wolde",
    title: "Calm Down",
    instructorSlug: "efrat-wolde",
    level: "all-levels",
    style: "afro",
    tags: ["afro", "performance"],
    songName: "Calm Down",
    artist: "Rema",
    bpm: "107 BPM",
    length: "3:39",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 70 },
      { id: "full-speed", time: 127 },
    ],
    checkoutHref: "/checkout/calm-down-efrat-wolde",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "dumebi-yonatan-tesfaye",
    title: "Dumebi",
    instructorSlug: "yonatan-tesfaye",
    level: "intermediate",
    style: "afro",
    tags: ["afro", "groove"],
    songName: "Dumebi",
    artist: "Rema",
    bpm: "104 BPM",
    length: "3:17",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 63 },
      { id: "full-speed", time: 114 },
    ],
    checkoutHref: "/checkout/dumebi-yonatan-tesfaye",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "love-nwantiti-efrat-wolde",
    title: "Love Nwantiti",
    instructorSlug: "efrat-wolde",
    level: "advanced",
    style: "afro",
    tags: ["afro", "musicality"],
    songName: "Love Nwantiti",
    artist: "CKay",
    bpm: "108 BPM",
    length: "2:47",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 20 },
      { id: "slow-practice", time: 53 },
      { id: "full-speed", time: 97 },
    ],
    checkoutHref: "/checkout/love-nwantiti-efrat-wolde",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "free-mind-yonatan-tesfaye",
    title: "Free Mind",
    instructorSlug: "yonatan-tesfaye",
    level: "all-levels",
    style: "afro",
    tags: ["afro", "body-control"],
    songName: "Free Mind",
    artist: "Tems",
    bpm: "105 BPM",
    length: "3:47",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 27 },
      { id: "slow-practice", time: 73 },
      { id: "full-speed", time: 132 },
    ],
    checkoutHref: "/checkout/free-mind-yonatan-tesfaye",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "peru-efrat-wolde",
    title: "Peru",
    instructorSlug: "efrat-wolde",
    level: "intermediate",
    style: "afro",
    tags: ["afro", "performance"],
    songName: "Peru",
    artist: "Fireboy DML",
    bpm: "103 BPM",
    length: "2:52",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 100 },
    ],
    checkoutHref: "/checkout/peru-efrat-wolde",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "rush-yonatan-tesfaye",
    title: "Rush",
    instructorSlug: "yonatan-tesfaye",
    level: "advanced",
    style: "afro",
    tags: ["afro", "groove"],
    songName: "Rush",
    artist: "Ayra Starr",
    bpm: "103 BPM",
    length: "2:50",
    poster: "/routine-poster-afro-sunburst.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 20 },
      { id: "slow-practice", time: 54 },
      { id: "full-speed", time: 99 },
    ],
    checkoutHref: "/checkout/rush-yonatan-tesfaye",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "terminator-or-katz",
    title: "Terminator",
    instructorSlug: "or-katz",
    level: "intermediate",
    style: "dancehall",
    tags: ["dancehall", "performance"],
    songName: "Terminator",
    artist: "Asake",
    bpm: "103 BPM",
    length: "2:53",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 55 },
      { id: "full-speed", time: 100 },
    ],
    checkoutHref: "/checkout/terminator-or-katz",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "touch-it-tamir-levy",
    title: "Touch It",
    instructorSlug: "tamir-levy",
    level: "advanced",
    style: "dancehall",
    tags: ["dancehall", "groove"],
    songName: "Touch It",
    artist: "KiDi",
    bpm: "105 BPM",
    length: "3:20",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/touch-it-tamir-levy",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "temperature-or-katz",
    title: "Temperature",
    instructorSlug: "or-katz",
    level: "all-levels",
    style: "dancehall",
    tags: ["dancehall", "musicality"],
    songName: "Temperature",
    artist: "Sean Paul",
    bpm: "98 BPM",
    length: "3:24",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 65 },
      { id: "full-speed", time: 118 },
    ],
    checkoutHref: "/checkout/temperature-or-katz",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "get-busy-tamir-levy",
    title: "Get Busy",
    instructorSlug: "tamir-levy",
    level: "intermediate",
    style: "dancehall",
    tags: ["dancehall", "body-control"],
    songName: "Get Busy",
    artist: "Sean Paul",
    bpm: "95 BPM",
    length: "3:36",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 69 },
      { id: "full-speed", time: 125 },
    ],
    checkoutHref: "/checkout/get-busy-tamir-levy",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "family-or-katz",
    title: "Family",
    instructorSlug: "or-katz",
    level: "advanced",
    style: "dancehall",
    tags: ["dancehall", "performance"],
    songName: "Family",
    artist: "Popcaan",
    bpm: "101 BPM",
    length: "3:20",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 24 },
      { id: "slow-practice", time: 64 },
      { id: "full-speed", time: 116 },
    ],
    checkoutHref: "/checkout/family-or-katz",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "ova-dweet-tamir-levy",
    title: "Ova Dweet",
    instructorSlug: "tamir-levy",
    level: "all-levels",
    style: "dancehall",
    tags: ["dancehall", "groove"],
    songName: "Ova Dweet",
    artist: "Popcaan",
    bpm: "100 BPM",
    length: "3:12",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 61 },
      { id: "full-speed", time: 111 },
    ],
    checkoutHref: "/checkout/ova-dweet-tamir-levy",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "blessed-or-katz",
    title: "Blessed",
    instructorSlug: "or-katz",
    level: "intermediate",
    style: "dancehall",
    tags: ["dancehall", "musicality"],
    songName: "Blessed",
    artist: "Shenseea",
    bpm: "100 BPM",
    length: "3:03",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 59 },
      { id: "full-speed", time: 106 },
    ],
    checkoutHref: "/checkout/blessed-or-katz",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "lick-tamir-levy",
    title: "Lick",
    instructorSlug: "tamir-levy",
    level: "advanced",
    style: "dancehall",
    tags: ["dancehall", "body-control"],
    songName: "Lick",
    artist: "Shenseea",
    bpm: "98 BPM",
    length: "3:07",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 60 },
      { id: "full-speed", time: 108 },
    ],
    checkoutHref: "/checkout/lick-tamir-levy",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "bruk-off-yuh-back-or-katz",
    title: "Bruk Off Yuh Back",
    instructorSlug: "or-katz",
    level: "all-levels",
    style: "dancehall",
    tags: ["dancehall", "performance"],
    songName: "Bruk Off Yuh Back",
    artist: "Konshens",
    bpm: "105 BPM",
    length: "3:05",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 59 },
      { id: "full-speed", time: 107 },
    ],
    checkoutHref: "/checkout/bruk-off-yuh-back-or-katz",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "fever-tamir-levy",
    title: "Fever",
    instructorSlug: "tamir-levy",
    level: "intermediate",
    style: "dancehall",
    tags: ["dancehall", "groove"],
    songName: "Fever",
    artist: "Vybz Kartel",
    bpm: "100 BPM",
    length: "3:12",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 61 },
      { id: "full-speed", time: 111 },
    ],
    checkoutHref: "/checkout/fever-tamir-levy",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "so-mi-like-it-or-katz",
    title: "So Mi Like It",
    instructorSlug: "or-katz",
    level: "advanced",
    style: "dancehall",
    tags: ["dancehall", "musicality"],
    songName: "So Mi Like It",
    artist: "Spice",
    bpm: "103 BPM",
    length: "2:58",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 57 },
      { id: "full-speed", time: 103 },
    ],
    checkoutHref: "/checkout/so-mi-like-it-or-katz",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "coke-tamir-levy",
    title: "Coke",
    instructorSlug: "tamir-levy",
    level: "all-levels",
    style: "dancehall",
    tags: ["dancehall", "body-control"],
    songName: "Coke",
    artist: "Skillibeng",
    bpm: "100 BPM",
    length: "2:40",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 51 },
      { id: "full-speed", time: 93 },
    ],
    checkoutHref: "/checkout/coke-tamir-levy",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "ina-real-life-or-katz",
    title: "Ina Real Life",
    instructorSlug: "or-katz",
    level: "intermediate",
    style: "dancehall",
    tags: ["dancehall", "performance"],
    songName: "Ina Real Life",
    artist: "Alkaline",
    bpm: "98 BPM",
    length: "3:10",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 23 },
      { id: "slow-practice", time: 61 },
      { id: "full-speed", time: 110 },
    ],
    checkoutHref: "/checkout/ina-real-life-or-katz",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "owe-me-nothing-tamir-levy",
    title: "Owe Me Nothing",
    instructorSlug: "tamir-levy",
    level: "advanced",
    style: "dancehall",
    tags: ["dancehall", "groove"],
    songName: "Owe Me Nothing",
    artist: "Dexta Daps",
    bpm: "95 BPM",
    length: "3:36",
    poster: "/routine-poster-dancehall-block.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 69 },
      { id: "full-speed", time: 125 },
    ],
    checkoutHref: "/checkout/owe-me-nothing-tamir-levy",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "cant-stop-the-feeling-michal-buzaglo",
    title: "Can't Stop the Feeling",
    instructorSlug: "michal-buzaglo",
    level: "intermediate",
    style: "voguing",
    tags: ["voguing", "performance"],
    songName: "Can't Stop the Feeling",
    artist: "Justin Timberlake",
    bpm: "113 BPM",
    length: "3:56",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 28 },
      { id: "slow-practice", time: 76 },
      { id: "full-speed", time: 137 },
    ],
    checkoutHref: "/checkout/cant-stop-the-feeling-michal-buzaglo",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "unholy-guy-ravid",
    title: "Unholy",
    instructorSlug: "guy-ravid",
    level: "advanced",
    style: "voguing",
    tags: ["voguing", "groove"],
    songName: "Unholy",
    artist: "Sam Smith ft. Kim Petras",
    bpm: "131 BPM",
    length: "2:36",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 50 },
      { id: "full-speed", time: 90 },
    ],
    checkoutHref: "/checkout/unholy-guy-ravid",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "unavailable-michal-buzaglo",
    title: "Unavailable",
    instructorSlug: "michal-buzaglo",
    level: "all-levels",
    style: "voguing",
    tags: ["voguing", "musicality"],
    songName: "Unavailable",
    artist: "Davido ft. Musa Keys",
    bpm: "107 BPM",
    length: "2:58",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 57 },
      { id: "full-speed", time: 103 },
    ],
    checkoutHref: "/checkout/unavailable-michal-buzaglo",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "calm-down-guy-ravid",
    title: "Calm Down",
    instructorSlug: "guy-ravid",
    level: "intermediate",
    style: "voguing",
    tags: ["voguing", "body-control"],
    songName: "Calm Down",
    artist: "Rema",
    bpm: "107 BPM",
    length: "3:39",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 70 },
      { id: "full-speed", time: 127 },
    ],
    checkoutHref: "/checkout/calm-down-guy-ravid",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "rush-michal-buzaglo",
    title: "Rush",
    instructorSlug: "michal-buzaglo",
    level: "advanced",
    style: "voguing",
    tags: ["voguing", "performance"],
    songName: "Rush",
    artist: "Ayra Starr",
    bpm: "103 BPM",
    length: "2:50",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 20 },
      { id: "slow-practice", time: 54 },
      { id: "full-speed", time: 99 },
    ],
    checkoutHref: "/checkout/rush-michal-buzaglo",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "sad-girlz-luv-money-guy-ravid",
    title: "Sad Girlz Luv Money",
    instructorSlug: "guy-ravid",
    level: "all-levels",
    style: "voguing",
    tags: ["voguing", "groove"],
    songName: "Sad Girlz Luv Money",
    artist: "Amaarae",
    bpm: "100 BPM",
    length: "2:37",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 19 },
      { id: "slow-practice", time: 50 },
      { id: "full-speed", time: 91 },
    ],
    checkoutHref: "/checkout/sad-girlz-luv-money-guy-ravid",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "blessed-michal-buzaglo",
    title: "Blessed",
    instructorSlug: "michal-buzaglo",
    level: "intermediate",
    style: "voguing",
    tags: ["voguing", "musicality"],
    songName: "Blessed",
    artist: "Shenseea",
    bpm: "100 BPM",
    length: "3:03",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 22 },
      { id: "slow-practice", time: 59 },
      { id: "full-speed", time: 106 },
    ],
    checkoutHref: "/checkout/blessed-michal-buzaglo",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "break-my-soul-guy-ravid",
    title: "Break My Soul",
    instructorSlug: "guy-ravid",
    level: "advanced",
    style: "voguing",
    tags: ["voguing", "body-control"],
    songName: "Break My Soul",
    artist: "Beyoncé",
    bpm: "115 BPM",
    length: "4:38",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 33 },
      { id: "slow-practice", time: 89 },
      { id: "full-speed", time: 161 },
    ],
    checkoutHref: "/checkout/break-my-soul-guy-ravid",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "formation-michal-buzaglo",
    title: "Formation",
    instructorSlug: "michal-buzaglo",
    level: "all-levels",
    style: "voguing",
    tags: ["voguing", "performance"],
    songName: "Formation",
    artist: "Beyoncé",
    bpm: "115 BPM",
    length: "3:26",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 25 },
      { id: "slow-practice", time: 66 },
      { id: "full-speed", time: 119 },
    ],
    checkoutHref: "/checkout/formation-michal-buzaglo",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
  {
    slug: "umbrella-guy-ravid",
    title: "Umbrella",
    instructorSlug: "guy-ravid",
    level: "intermediate",
    style: "voguing",
    tags: ["voguing", "groove"],
    songName: "Umbrella",
    artist: "Rihanna",
    bpm: "87 BPM",
    length: "4:36",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 33 },
      { id: "slow-practice", time: 88 },
      { id: "full-speed", time: 160 },
    ],
    checkoutHref: "/checkout/umbrella-guy-ravid",
    pricing: {
      original: 59,
      earlyBird: 39,
    },
  },
  {
    slug: "dont-stop-the-music-michal-buzaglo",
    title: "Don't Stop the Music",
    instructorSlug: "michal-buzaglo",
    level: "advanced",
    style: "voguing",
    tags: ["voguing", "musicality"],
    songName: "Don't Stop the Music",
    artist: "Rihanna",
    bpm: "123 BPM",
    length: "4:33",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 33 },
      { id: "slow-practice", time: 87 },
      { id: "full-speed", time: 158 },
    ],
    checkoutHref: "/checkout/dont-stop-the-music-michal-buzaglo",
    pricing: {
      original: 69,
      earlyBird: 49,
    },
  },
  {
    slug: "7-rings-guy-ravid",
    title: "7 rings",
    instructorSlug: "guy-ravid",
    level: "all-levels",
    style: "voguing",
    tags: ["voguing", "body-control"],
    songName: "7 rings",
    artist: "Ariana Grande",
    bpm: "140 BPM",
    length: "2:58",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 21 },
      { id: "slow-practice", time: 57 },
      { id: "full-speed", time: 103 },
    ],
    checkoutHref: "/checkout/7-rings-guy-ravid",
    pricing: {
      original: 79,
      earlyBird: 59,
    },
  },
  {
    slug: "break-free-michal-buzaglo",
    title: "Break Free",
    instructorSlug: "michal-buzaglo",
    level: "intermediate",
    style: "voguing",
    tags: ["voguing", "performance"],
    songName: "Break Free",
    artist: "Ariana Grande",
    bpm: "128 BPM",
    length: "3:34",
    poster: "/routine-poster-voguing-spotlight.png",
    videoSrc: SAMPLE_VIDEO_SRC,
    chapters: [
      { id: "full-performance", time: 0 },
      { id: "breakdown", time: 26 },
      { id: "slow-practice", time: 68 },
      { id: "full-speed", time: 124 },
    ],
    checkoutHref: "/checkout/break-free-michal-buzaglo",
    pricing: {
      original: 49,
      earlyBird: 29,
    },
  },
];

export function getAllRoutines(): RoutineRecord[] {
  return ROUTINES;
}

export function getRoutineBySlug(slug: string): RoutineRecord | undefined {
  return ROUTINES.find((routine) => routine.slug === slug);
}

export function getRoutinesByInstructor(instructorSlug: string): RoutineRecord[] {
  return ROUTINES.filter((routine) => routine.instructorSlug === instructorSlug);
}

export interface RoutinesFilterParams {
  /** A single slug, or several for the multi-select teacher filter (joined as `a,b,c` in the URL). */
  instructor?: string | string[];
  style?: string;
  level?: string;
  locale?: Locale;
}

/** Build a locale-aware tutorials catalog URL from the active filters. */
export function routinesFilterHref({
  instructor,
  style,
  level,
  locale = "he",
}: RoutinesFilterParams): string {
  const params = new URLSearchParams();
  const instructorValue = Array.isArray(instructor)
    ? instructor.filter(Boolean).join(",")
    : instructor;
  if (instructorValue) params.set("instructor", instructorValue);
  if (style) params.set("style", style);
  if (level) params.set("level", level);
  const query = params.toString();
  const base = localePath(locale, "/routines");
  return query ? `${base}?${query}` : base;
}
