# Creates .env.local from a pasted Firebase web config.
# Usage (PowerShell):
#   1. Copy the firebaseConfig { ... } block from Firebase console
#   2. Run:  .\scripts\write-firebase-env.ps1
#   3. Paste when prompted, then press Enter twice (blank line to finish)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$target = Join-Path $root ".env.local"

Write-Host ""
Write-Host "Paste the Firebase web config object (the { apiKey: ... } block)."
Write-Host "When done, press Enter on an empty line."
Write-Host ""

$lines = @()
while ($true) {
  $line = Read-Host
  if ([string]::IsNullOrWhiteSpace($line)) { break }
  $lines += $line
}

$text = ($lines -join "`n")

function Get-ConfigValue([string]$source, [string]$key) {
  $patterns = @(
    "['`"]$key['`"]\s*:\s*['`"]([^'`"]+)['`"]",
    "$key\s*:\s*[`"]([^`"]+)[`"]"
  )
  foreach ($pattern in $patterns) {
    $match = [regex]::Match($source, $pattern)
    if ($match.Success) { return $match.Groups[1].Value }
  }
  return $null
}

$apiKey = Get-ConfigValue $text "apiKey"
$authDomain = Get-ConfigValue $text "authDomain"
$projectId = Get-ConfigValue $text "projectId"
$storageBucket = Get-ConfigValue $text "storageBucket"
$messagingSenderId = Get-ConfigValue $text "messagingSenderId"
$appId = Get-ConfigValue $text "appId"

$missing = @()
if (-not $apiKey) { $missing += "apiKey" }
if (-not $authDomain) { $missing += "authDomain" }
if (-not $projectId) { $missing += "projectId" }
if (-not $storageBucket) { $missing += "storageBucket" }
if (-not $messagingSenderId) { $missing += "messagingSenderId" }
if (-not $appId) { $missing += "appId" }

if ($missing.Count -gt 0) {
  Write-Host "Could not find: $($missing -join ', ')" -ForegroundColor Red
  Write-Host "Paste the full firebaseConfig object and try again."
  exit 1
}

$siteUrl = ""
if (Test-Path $target) {
  $existing = Get-Content $target -Raw
  $siteMatch = [regex]::Match($existing, "NEXT_PUBLIC_SITE_URL=(.*)")
  if ($siteMatch.Success) { $siteUrl = $siteMatch.Groups[1].Value.Trim() }
}

@"
# Generated by scripts/write-firebase-env.ps1 — do not commit.

NEXT_PUBLIC_FIREBASE_API_KEY=$apiKey
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$authDomain
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$projectId
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$storageBucket
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId
NEXT_PUBLIC_FIREBASE_APP_ID=$appId

NEXT_PUBLIC_SITE_URL=$siteUrl
"@ | Set-Content -Path $target -Encoding utf8

Write-Host ""
Write-Host "Wrote $target" -ForegroundColor Green
Write-Host "Project: $projectId"
Write-Host "Restart next dev, then open /he/login and try Google."
